const DAY = 86400000;
const cityLabels={chiangmai:'清迈',sukhothai:'素可泰',chiangrai:'清莱',bangkok:'曼谷',maeklong:'美功与丹嫩',ayutthaya:'大城'};
const typeColors={core:'#176052',optional:'#d8872c',food:'#b84835',drink:'#76513b',indoor:'#386b8a',transport:'#645a87'};
const typeLabels={core:'核心',food:'餐饮',drink:'咖啡',indoor:'雨天',transport:'交通',optional:'可选'};

const places=[
  {id:'wat-phra-singh',city:'chiangmai',name:'Wat Phra Singh 帕辛寺',lat:18.788586,lng:98.98201,type:'core',desc:'清迈最受尊崇的寺庙之一。老城步行日从这里开始，能先看懂兰纳木构、金色装饰和城市信仰。'},
  {id:'wat-chedi-luang',city:'chiangmai',name:'Wat Chedi Luang 契迪龙寺',lat:18.786988,lng:98.98652,type:'core',desc:'15 世纪巨型佛塔遗迹。它的残缺尺度比一座修得完整的寺庙更能让人记住。'},
  {id:'wat-phan-tao',city:'chiangmai',name:'Wat Phan Tao 潘道寺',lat:18.787662,lng:98.987814,type:'core',desc:'深色柚木大殿紧邻契迪龙寺。只停十几分钟，也能让老城这一段的材质变化变得很清楚。'},
  {id:'lanna-museum',city:'chiangmai',name:'Lanna Folklife Museum 兰纳民俗馆',lat:18.790191,lng:98.988039,type:'indoor',desc:'把寺庙里看见的建筑、信仰和日常器物重新串起来。热或下雨时比继续赶寺庙更合适。'},
  {id:'warorot',city:'chiangmai',name:'Talat Warorot 瓦洛洛市场',lat:18.790557,lng:99.000582,type:'core',desc:'老市场里的香肠、猪皮、辣椒酱、布料和家用品混在一起，清迈从古城走回日常生活就在这里。'},
  {id:'monks-trail',city:'chiangmai',name:"Monk's Trail 起点",lat:18.79608,lng:98.95131,type:'optional',desc:'到 Wat Pha Lat 通常约 45–60 分钟。雨后石面和土路湿滑时，我们直接改坐红车。'},
  {id:'wat-pha-lat',city:'chiangmai',name:'Wat Pha Lat 帕拉寺',lat:18.79865,lng:98.93415,type:'core',desc:'半山上的林寺，石阶、那伽和水声把空间藏进树林里。这里值得慢，不值得冒雨硬走。'},
  {id:'doi-suthep',city:'chiangmai',name:'Wat Phra That Doi Suthep 双龙寺',lat:18.80485,lng:98.92157,type:'core',desc:'清迈最重要的山寺。低云会拿走城市远景，却拿不走金色佛塔、回廊和香火。'},
  {id:'wat-umong',city:'chiangmai',name:'Wat Umong 悟孟寺',lat:18.78302,lng:98.95233,type:'optional',desc:'林中的隧道寺庙。它和手作社区只能二选一，留给当天体力和雨势决定。'},
  {id:'baan-kang-wat',city:'chiangmai',name:'Baan Kang Wat 艺术村',lat:18.78578,lng:98.95249,type:'optional',desc:'小型工作室、陶艺、咖啡和树荫庭院。我们来这里是为了松下来，不是收集每一家店。'},
  {id:'ang-kaew',city:'chiangmai',name:'Ang Kaew Reservoir 安娇湖',lat:18.80507,lng:98.95218,type:'core',desc:'清迈大学山脚下的湖和环湖步道。我把它留在傍晚，好让喝完咖啡以后还有一段不需要完成任务的路。'},
  {id:'cmu-art-center',city:'chiangmai',name:'CMU Art Center 清迈大学艺术中心',lat:18.79522,lng:98.96842,type:'indoor',desc:'宁曼和校园之间的展览空间。具体展览临近出发再看，雨天可以自然接住半个下午。'},
  {id:'ristr8to',city:'chiangmai',name:'Ristr8to Original',lat:18.79936,lng:98.96815,type:'drink',desc:'宁曼代表性的专业咖啡店。想喝就去，排队太长就换附近独立店，不让一个店名绑住下午。'},
  {id:'one-nimman',city:'chiangmai',name:'One Nimman 与宁曼小巷',lat:18.80078,lng:98.96839,type:'optional',desc:'咖啡、晚饭和雨后散步都能留在这一小圈。它更像收尾位置，不是必须打卡的商场。'},
  {id:'elephant-nature-park',city:'chiangmai',name:'Elephant Nature Park 大象保护区',lat:19.2141,lng:98.8584,type:'core',desc:'在湄登的救助与庇护园区。我们选远距离观察的项目，不骑象、不看表演，也不把洗象和摸象当互动福利。'},
  {id:'night-safari',city:'chiangmai',name:'Chiang Mai Night Safari 夜间动物园',lat:18.7423,lng:98.9167,type:'optional',desc:'傍晚搭园区电车观察动物的远郊模块。它会占掉整个夜晚，和安娇湖、宁曼夜市是替换关系。'},
  {id:'jing-jai',city:'chiangmai',name:'Jing Jai Weekend Market（JJ Market）',lat:18.8112,lng:98.9994,type:'core',desc:'周末清晨才最值得来的农夫与手作市集。我们把它放在飞曼谷前的早上，吃早餐、看手作，11 点左右离开。'},
  {id:'nong-ho',city:'chiangmai',name:'Nong Ho Flea Market',lat:18.82101,lng:98.97217,type:'optional',desc:'更像真正的跳蚤与后备箱市集，二手衣物、唱片和杂物比精致手作多。只在周末早上用它替换 JJ。'},
  {id:'lila-oldcity',city:'chiangmai',name:'Lila Thai Massage 老城店',lat:18.7894,lng:98.9901,type:'optional',desc:'老城步行日最顺的按摩落点。它为受训的前女性服刑人员提供就业，我们会先预约合适时段。'},
  {id:'doi-inthanon',city:'chiangmai',name:'Doi Inthanon 茵他侬山',lat:18.5887,lng:98.48606,type:'optional',desc:'泰国最高峰。雨季苔藓和瀑布状态好，能见度却无法保证，只能当晴天分支。'},
  {id:'wachirathan',city:'chiangmai',name:'Wachirathan Waterfall',lat:18.5414,lng:98.5995,type:'optional',desc:'雨季水量和飞沫都很强。防滑鞋与防水袋比雨伞更有用。'},
  {id:'sp-chicken',city:'chiangmai',name:'SP Chicken',lat:18.78756,lng:98.981516,type:'food',desc:'帕辛寺附近的烤鸡和 Isan 配菜，适合把老城上午收得简单。'},
  {id:'khao-soi-lamduan',city:'chiangmai',name:'Khao Soi Lam Duan',lat:18.801567,lng:99.005442,type:'food',desc:'Warorot 以北的传统咖喱面。营业状态临近出发复核。'},
  {id:'north-gate-jazz',city:'chiangmai',name:'North Gate Jazz Co-Op',lat:18.795154,lng:98.986922,type:'core',desc:'老城北门边的现场爵士。早到比较容易站得舒服，太累就把它留给另一个晚上。'},
  {id:'white-temple',city:'chiangrai',name:'Wat Rong Khun 白庙',lat:19.82419,lng:99.76313,type:'core',desc:'当代艺术家 Chalermchai Kositpipat 持续建造的白色寺庙艺术工程。'},
  {id:'blue-temple',city:'chiangrai',name:'Wat Rong Suea Ten 蓝庙',lat:19.92346,lng:99.84172,type:'core',desc:'蓝金色室内外视觉强烈，适合清迈抵达清莱后的傍晚。'},
  {id:'baan-dam',city:'chiangrai',name:'Baan Dam 黑屋博物馆',lat:19.99225,lng:99.86053,type:'optional',desc:'Thawan Duchanee 的黑色建筑与艺术集合，和白庙构成鲜明对照。'},
  {id:'clock-tower',city:'chiangrai',name:'Chiang Rai Clock Tower',lat:19.90701,lng:99.83067,type:'optional',desc:'市中心晚间落点，周围便于吃饭与住宿。'},
  {id:'cei',city:'chiangrai',name:'Chiang Rai Airport CEI',lat:19.95234,lng:99.88293,type:'transport',desc:'清莱备选路线从这里直飞曼谷，避免返回清迈。'},
  {id:'sukhothai-mahathat',city:'sukhothai',name:'Wat Mahathat 素可泰玛哈泰寺',lat:17.01694,lng:99.70314,type:'core',desc:'历史公园的中心。莲花苞式主塔、佛像和水面在傍晚形成整趟路线里最安静的一段。'},
  {id:'wat-sa-si',city:'sukhothai',name:'Wat Sa Si 沙西寺',lat:17.01972,lng:99.69936,type:'core',desc:'池中小岛上的佛塔和行走佛。我们等日落前再来，不用在正午匆匆拍完。'},
  {id:'wat-si-chum',city:'sukhothai',name:'Wat Si Chum 西春寺',lat:17.02677,lng:99.69362,type:'core',desc:'狭窄佛殿里坐着巨大的 Phra Achana 佛像，尺度和空间感与清迈、曼谷都不同。'},
  {id:'sukhothai-cafe',city:'sukhothai',name:'Cafe Thammada',lat:17.01779,lng:99.70491,type:'drink',desc:'历史公园入口附近的冷气和冰饮停靠点。当天营业状态要复查。'},
  {id:'ths',city:'sukhothai',name:'Sukhothai Airport THS',lat:17.23804,lng:99.81818,type:'transport',desc:'素可泰开口路线的关键。班次少，出票前必须重新核对飞曼谷的时间。'},
  {id:'grand-palace',city:'bangkok',name:'Grand Palace 与 Wat Phra Kaew',lat:13.75002,lng:100.49129,type:'core',desc:'曼谷王城主轴。我们早到，把最需要体力和注意力的地方放在热起来之前。'},
  {id:'wat-pho',city:'bangkok',name:'Wat Pho 卧佛寺',lat:13.746553,lng:100.49334,type:'core',desc:'卧佛、佛塔和传统医药历史放在同一座寺院里。看完王宫走过来最顺。'},
  {id:'wat-arun',city:'bangkok',name:'Wat Arun 郑王庙',lat:13.743766,lng:100.488938,type:'core',desc:'从 Tha Tien 过河后，瓷片镶嵌的高塔会从远景变成能看清材质的建筑。'},
  {id:'after-khok-wua',city:'bangkok',name:'After Khok Wua 公交站',lat:13.75824,lng:100.49876,type:'transport',desc:'大皇宫步行线的可选起点。511 只有酒店正好在其走廊上才方便，不是曼谷任意位置都能直接搭到这里。'},
  {id:'tha-tien',city:'bangkok',name:'Tha Tien Pier 卧佛寺码头',lat:13.74618,lng:100.49046,type:'transport',desc:'卧佛寺与郑王庙之间的短途过河码头。现场认准过河摆渡，不要把观光船与通勤船混在一起。'},
  {id:'mama-cafe',city:'bangkok',name:'Mama Cafe（Buddha Front）',lat:13.7228,lng:100.4672,type:'drink',desc:'Phet Kasem 15 巷里的大佛正面取景点。网上常被误写成 Mama Cooking，导航时要核对 60–62 号与店铺照片。'},
  {id:'wat-pradu',city:'bangkok',name:'Wat Pradu Chimphli',lat:13.72424,lng:100.46975,type:'core',desc:'能把水门寺大佛与观音像放进同一视线的社区寺院。这里首先是礼佛空间，拍照不要挡住进出和仪式。'},
  {id:'wat-paknam',city:'bangkok',name:'Wat Paknam Phasi Charoen 水门寺',lat:13.7215,lng:100.4708,type:'core',desc:'吞武里运河边的皇家寺院，大佛与塔内玻璃佛塔是视觉焦点。我们会在 17 点前到，不拿网上互相矛盾的闭门时间冒险。'},
  {id:'wat-paknam-bridge',city:'bangkok',name:'水门寺大佛背影桥位',lat:13.7199,lng:100.4714,type:'optional',desc:'社区桥上的大佛背影机位，不是正式景点。只走有标识的公共出口与道路，不穿商贩或住户的私人通道。'},
  {id:'at-talat-phlu',city:'bangkok',name:'AT TALAT PHLU 天台咖啡',lat:13.72006,lng:100.4738,type:'drink',desc:'从二、三层露台看大佛与吞武里屋顶的收尾位置。营业和露台规则会变，出发当天再确认。'},
  {id:'flower-market',city:'bangkok',name:'Pak Khlong Talat 花市',lat:13.74198,lng:100.49955,type:'optional',desc:'王城线的傍晚补充。累了就删，不需要为了最热闹的时段熬夜。'},
  {id:'talat-noi',city:'bangkok',name:'Talat Noi',lat:13.733747,lng:100.513047,type:'core',desc:'修车铺、老宅、宗祠、街头艺术与河岸叠在一起的步行片区。'},
  {id:'yaowarat',city:'bangkok',name:'Yaowarat Road 唐人街',lat:13.73944,lng:100.51153,type:'core',desc:'夜间小吃主轴。我们从 Talat Noi 慢慢走来，每站只分着吃一两样。'},
  {id:'wat-traimit',city:'bangkok',name:'Wat Traimit 金佛寺',lat:13.738133,lng:100.513728,type:'optional',desc:'靠近唐人街入口。下午来得及就作为文化起点，闭馆后直接从街区开始。'},
  {id:'jim-thompson',city:'bangkok',name:'Jim Thompson House',lat:13.749246,lng:100.528373,type:'indoor',desc:'六座泰式木屋、丝绸产业和收藏史。下雨友好，但庭院和楼梯仍需要走。'},
  {id:'bacc',city:'bangkok',name:'Bangkok Art & Culture Centre',lat:13.746604,lng:100.530069,type:'indoor',desc:'Siam 一带最稳的雨天停靠点。官方目前周二至周日开放，周一闭馆。'},
  {id:'lumphini',city:'bangkok',name:'Lumphini Park',lat:13.731298,lng:100.541704,type:'optional',desc:'清晨或傍晚散步。雨后草地泥泞时改走硬质步道。'},
  {id:'benjakitti',city:'bangkok',name:'Benjakitti Forest Park',lat:13.72695,lng:100.55948,type:'optional',desc:'湿地式城市公园和高架步道，适合现代曼谷半日的日落。'},
  {id:'mahanakhon',city:'bangkok',name:'King Power Mahanakhon',lat:13.723033,lng:100.528282,type:'optional',desc:'低云或雷雨时不提前锁定不可退票时段。'},
  {id:'chatuchak',city:'bangkok',name:'Chatuchak Weekend Market',lat:13.799923,lng:100.550824,type:'optional',desc:'周末才最完整。我们早去、先逛目标区，午后闷热前离开。'},
  {id:'or-tor-kor',city:'bangkok',name:'Or Tor Kor Market',lat:13.80187,lng:100.54812,type:'food',desc:'Chatuchak 对面更适合稳定吃午饭和买水果的市场。'},
  {id:'krua-apsorn',city:'bangkok',name:'Krua Apsorn (Dusit)',lat:13.774202,lng:100.506363,type:'food',desc:'中央与南部泰菜，是否仍获当年推荐以及营业时间临近再核。'},
  {id:'jok-prince',city:'bangkok',name:'Jok Prince',lat:13.72072,lng:100.51456,type:'food',desc:'Charoen Krung 的老牌泰式粥。它和 Talat Noi 同方向，但别为了绕路硬塞。'},
  {id:'wongwian-yai-srt',city:'maeklong',name:'Wongwian Yai SRT 火车站',lat:13.72442,lng:100.49129,type:'transport',desc:'美功铁路东段的曼谷起点，不是 BTS 同名站。DIY 版本要在这里搭 07:40 普通列车。'},
  {id:'mahachai-station',city:'maeklong',name:'Mahachai Railway Station',lat:13.5467,lng:100.274,type:'transport',desc:'08:39 左右抵达后穿过市场走向河边。铁路在这里断开，下一段需要先坐渡轮。'},
  {id:'mahachai-ferry',city:'maeklong',name:'Mahachai Ferry Pier',lat:13.5478,lng:100.2722,type:'transport',desc:'横渡 Tha Chin River 的短程渡轮。过河后还要步行去 Ban Laem 站，不能在 Mahachai 原站直接换车。'},
  {id:'ban-laem-station',city:'maeklong',name:'Ban Laem Railway Station',lat:13.54193,lng:100.26989,type:'transport',desc:'美功铁路西段起点。DIY 路线要赶 10:10 发车，渡轮和步行都要留余量。'},
  {id:'maeklong-market',city:'maeklong',name:'Mae Klong Railway Market 美功铁道市场',lat:13.40789,lng:100.00103,type:'core',desc:'列车沿着摊位之间的轨道慢慢进站，遮棚在到车前收起。11:10 到站和 11:30 发车是当前最好衔接的观察窗口。'},
  {id:'samutsongkhram-bus',city:'maeklong',name:'Samut Songkhram Bus Terminal',lat:13.4099,lng:100.0004,type:'transport',desc:'从美功去丹嫩或回曼谷时常用的公路接驳点。班次与上车点可能调整，现场先问清终点。'},
  {id:'damnoen-saduak',city:'maeklong',name:'Damnoen Saduak Floating Market 丹嫩沙多水上市场',lat:13.51886,lng:99.95949,type:'optional',desc:'清晨七到九点最有水上市集的工作感，接近中午会明显转成观光与空档。想和美功同日完成，就要先来这里。'},
  {id:'ayutthaya-mahathat',city:'ayutthaya',name:'Wat Mahathat 大城玛哈泰寺',lat:14.35692,lng:100.56848,type:'optional',desc:'树根佛头和高棉式塔群，是阿瑜陀耶最直观的遗址入口。'},
  {id:'ayutthaya-sanphet',city:'ayutthaya',name:'Wat Phra Si Sanphet',lat:14.35501,lng:100.55831,type:'optional',desc:'旧王宫范围内三座并列佛塔，能看出王城尺度。'},
  {id:'ayutthaya-chai',city:'ayutthaya',name:'Wat Chaiwatthanaram',lat:14.34294,lng:100.54152,type:'optional',desc:'位于河西岸，傍晚光线好，通常需要嘟嘟车或包车衔接。'}
];

const lp={title:'Lonely Planet Thailand 18th Edition',note:'已上传电子书。这里仅转述与现场观察有关的背景，不复制书中长段文字。'};
const src=(title,url,kind='官方')=>({title,url,kind});
const details={
  'wat-phra-singh':{imageFile:'20171105 Golden elephant statue of the Wat Phra Singh temple, Chiang Mai, Thailand 9843 DxO.jpg',why:'我想从这里开始老城，不只是因为它有名。先看过帕辛寺的木构、金色纹样和香火，我们后面走到几座小寺时会更容易分辨兰纳建筑的语气。',story:'寺院因供奉 Phra Singh 佛像而受敬重。现存空间经历多次修建，不能把它当成某一个年代原封不动留下的作品。Lonely Planet 特别提醒主佛殿与马赛克装饰，也提到 14 世纪佛塔的王室背景。',lookFor:['先看 Viharn Lai Kham 较低的屋檐和金色外墙，它和大殿的尺度不一样','绕到佛塔附近找大象托举的造型，再看礼佛的人如何使用回廊','进殿前留意鞋子、肩膝遮盖和拍照提示'],together:'我们早上先到这里，慢慢走完再向东去潘道寺。若当天很热，后面博物馆和市场只留一个。',rain:'短雨可以在廊下等。暴雨时寺内石面会滑，缩短室外停留，直接转兰纳民俗馆。',current:['宗教场所的仪式和局部开放会临时变化','衣着覆盖肩膝，进殿脱鞋'],sources:[lp,src('Tourism Authority of Thailand · Chiang Mai temple route','https://www.tourismthailand.org/Articles/self-driving-chiang-mai')]},
  'wat-phan-tao':{imageFile:'Wat Phan Tao Chiang Mai Thailand.jpg',why:'它紧贴契迪龙寺，却把材质从砖和灰泥一下换成深色柚木。我们不用停很久，这个转折本身就值得看。',story:'Lonely Planet 把这座大殿的柚木结构和 28 根木柱作为观察重点。它曾与王室建筑材料和工匠传统有关，今天看到的空间也经过修缮。',lookFor:['正面木墙在阳光和阴天里的颜色差别','门楣上的孔雀与狗年生肖线索','殿内连续木柱造成的纵深'],together:'从帕辛寺一路向东，先看潘道寺，再步行几分钟到契迪龙寺。',rain:'大殿能挡一阵雨，但庭院积水时不要久留。',sources:[lp]},
  'wat-chedi-luang':{imageFile:'20171105 Wat Chedi Luang Chiang Mai 9897 DxO.jpg',why:'它没有被修回“完整”，反而让人直接感到这座城曾经想把佛塔建到多大。我会把它留在上午最后一站。',story:'佛塔在 15 世纪上半叶达到高耸规模，玉佛曾在这里供奉。顶部后来坍毁，成因在地震与战事说法之间并不完全一致。20 世纪末的加固修复也引发过形态讨论。',lookFor:['四面台阶、佛龛和残缺上部之间的比例','基座上的石象哪些是修复补入，哪些保留较旧形态','从树荫下退远一点看佛塔如何压住周围屋顶'],together:'看完这里就停寺庙线。我们去吃饭、午休，下午只在民俗馆和 Warorot 里选一个。',rain:'砖石在大雨里很滑，雷雨时不要绕塔久走。',sources:[lp,src('Tourism Authority of Thailand · Chiang Mai route','https://www.tourismthailand.org/Articles/self-driving-chiang-mai')]},
  'lanna-museum':{imageFile:'Exhibit at Lanna Folklife Museum - Chiang Mai - Thailand (35098001366).jpg',why:'上午寺庙看多了容易只剩“金色很好看”。这里能把建筑、仪式和日常器物重新接回去，下雨时尤其合适。',story:'展陈围绕兰纳地区的宗教、生活与手工艺。它适合作为理解工具，不需要逐柜读完。',lookFor:['寺庙屋顶与木构模型','节庆、供品和服饰如何对应前面见到的空间','城市与山区文化在展陈里如何被区分'],together:'我们只挑两三个主题看，控制在一小时左右。若当日闭馆，就把时间给 Warorot。',rain:'这是老城最稳的室内替代之一。开放日和票价出发前在当地官方页面复核。',sources:[lp,src('TAT · Chiang Mai cultural route','https://www.tourismthailand.org/Articles/self-driving-chiang-mai')]},
  'warorot':{imageFile:'Warorot Market 01.jpg',why:'看完寺庙以后，我想和你走进一座还在过日子的市场。这里的重点不在“网红小吃”，而在清迈怎样买菜、买干货、买衣料。',story:'Lonely Planet 把它描述为清迈最早的一批公共市场之一。市场靠河并非偶然，过去农产和货物很大部分由水路到达，邻近的花市也延续了这一带的交易功能。',lookFor:['楼层之间从熟食、干货到布料和家用品的变化','北泰香肠、猪皮和辣椒酱如何摆在一起卖','走到河边时看市场与码头、花市的距离'],together:'我们下午坐双条车或 Grab 从老城到这里。想吃就分着买一点，不把晚饭吃死。',rain:'市场主体能避雨，过街和河边仍会湿滑。暴雨时缩短河边段。',sources:[lp]},
  'north-gate-jazz':{why:'如果当天还有精神，我们在北门边听一会儿现场。它是可以随时放弃的夜晚，不是必须完成的收尾。',story:'这里长期以拥挤、直接、离演奏者很近的现场氛围出名。演出安排与入场方式会变化。',lookFor:['当晚黑板或社交账号上的演出安排','室内外站位和音量差别','演出开始前先确认回酒店的车'],together:'从市场回酒店休息后再决定。到得晚没位置，就在附近喝一杯然后回去。',rain:'雨会让门口站位更拥挤，暴雨时不专程去。',sources:[lp]},
  'monks-trail':{imageFile:'Monks Trail Chiang Mai.jpg',why:'天气合适时，这段上山路能让帕拉寺的出现更有层次。可一旦连续下雨，它就不值得拿滑倒风险来换。',story:'Lonely Planet 给出的传统步行参考是到 Wat Pha Lat 约 45 分钟，再继续到双龙寺还要约 75 分钟。路况和体力差异很大，我们只把第一段当选项。',lookFor:['树上或路旁的僧衣色路标','湿石、裸露树根和排水沟','到寺院前水声逐渐变近'],together:'早上先看地面。干爽才走到帕拉寺，之后坐红车继续上山，不把整条山路当挑战。',rain:'前夜大雨、当天雷雨或鞋底不合适，直接取消步行。',sources:[lp,src('TAT · Doi Suthep and Wat Pha Lat route','https://www.tourismthailand.org/Articles/self-driving-chiang-mai')]},
  'wat-pha-lat':{imageFile:'Chiang Mai - Wat Pha Lat - 0001.jpg',why:'我更想和你在这里慢一点。寺庙被树、坡地和水声拆成许多小空间，不用站在正面拍一张就走。',story:'寺院与白象选择素贴山圣地的传说相连，但传说不能当成可证实的历史。20 世纪公路开通前后，寺院作为歇脚与修行空间的角色发生了变化。',lookFor:['那伽石阶如何顺着坡度进入树林','小瀑布和岩石怎样成为寺院空间的一部分','退到下方看屋顶从树叶间露出来'],together:'如果走 Monk’s Trail，我们到这里先休息。若坐车来，也不要一下车就赶双龙寺，至少留四十分钟。',rain:'小雨很美，暴雨和雷声出现就离开水边、石阶和林下。',sources:[lp,src('TAT · Wat Pha Lat','https://www.tourismthailand.org/Articles/self-driving-chiang-mai')]},
  'doi-suthep':{imageFile:'Phra That Doi Suthep 01.jpg',why:'它名气大，但仍值得。我们来看清迈如何把一座山寺当成城市信仰中心，也看它与山下城区的关系。',story:'寺院创建历史与白象选址传说交织。306 级那伽阶梯是到达仪式的一部分，金色佛塔和回廊则构成寺院核心。',lookFor:['那伽阶梯从山门到平台的视线变化','金色佛塔周围礼佛和绕行的方向','低云时把注意力从观景台转到回廊、铃铛和屋顶'],together:'我们坐红车上山，不把步行和观景都当必需。下山后直接回宁曼喝咖啡。',rain:'雷雨时不在观景台和外廊久停。大雨可缩短或整段取消。',current:['寺院开放、缆车和交通管制可能临时调整','进入核心区域覆盖肩膝并脱鞋'],sources:[lp,src('TAT · Wat Phra That Doi Suthep','https://www.tourismthailand.org/Attraction/wat-phra-that-doi-suthep')]},
  'wat-umong':{imageFile:'Tunnels at Wat Umong Suan Phutthatham-10.jpg',why:'如果山寺之后我们还想要安静，就来这里看林地和隧道。若更想喝咖啡、逛小店，就换 Baan Kang Wat。',story:'寺院以砖砌隧道与林地环境著称，今天的体验既有宗教空间，也有公园式散步。',lookFor:['隧道内声音和温度的变化','壁龛与通道如何组织礼佛方向','林地里的佛头与树根'],together:'它和 Baan Kang Wat 距离近，下午只选一个主角。',rain:'隧道可避短雨，入口与林地仍会滑。',sources:[lp]},
  'baan-kang-wat':{why:'我把它放在山下，是给我们一个不用继续“看景点”的下午。挑一家工作室、喝点东西就够了。',story:'这是由小型工作室、店铺与公共庭院组成的创意社区。商户独立营业，不能把整个园区的状态当成固定不变。',lookFor:['工作室与院落之间的步行尺度','陶艺、印刷和织物店各自的制作痕迹','树荫和座位是否适合当日雨势'],together:'从 Wat Umong 过来很近。若店铺休息，就直接去 CMU Art Center 或宁曼。',rain:'中雨可逛有顶空间，暴雨时出入口和庭院仍不舒服。',sources:[src('Baan Kang Wat · Instagram/现场信息','https://www.google.com/maps/search/?api=1&query=Baan+Kang+Wat+Chiang+Mai','现场复核')]},
  'ristr8to':{why:'清迈大学附近喝咖啡当然要有。我选它是因为咖啡本身，不是为了端着一杯拍照。',story:'Ristr8to 以意式咖啡、奶咖和竞赛经历出名，宁曼店客流也因此不稳定。菜单与营业时间临近再看。',lookFor:['先看当天豆单和浓缩基底再点','两个人可以一杯奶咖加一杯手冲或浓缩分着试','排队超过二十分钟就把附近独立店当同等选项'],together:'我们睡够再来。喝完往 CMU Art Center 或安娇湖走，不另外跨城。',rain:'咖啡馆能避雨，门口排队和座位才是变量。',sources:[src('Ristr8to · Google Maps 实时信息','https://www.google.com/maps/search/?api=1&query=Ristr8to+Original+Chiang+Mai','现场复核')]},
  'cmu-art-center':{why:'如果下午下雨，我们不必在商场里耗着。这里有展览可看，也正好在宁曼和校园之间。',story:'清迈大学艺术与文化中心承担展览、研究和兰纳文化保存。附近的兰纳传统民居博物馆由多座住宅和粮仓组成，开放安排与艺术中心不同。',lookFor:['先在官网看当前展览标题，避免空跑','建筑或民居里木构、抬高地面和通风方式','把展览内容与上午寺庙或市场看见的材料相互印证'],together:'我们只在展览确实想看时进去。晴天也可以直接跳过，把时间留给湖边。',rain:'这是清迈西侧最稳的雨天替代。艺术中心与传统民居的开放日要分别确认。',current:['艺术文化中心官网写常规办公开放为周一至周五 08:30–16:30','兰纳传统民居博物馆官网写周二至周日 08:30–16:30'],sources:[src('Chiang Mai University Art & Culture Center','https://artculture.cmu.ac.th/en/')]},
  'ang-kaew':{imageFile:'อ่างแก้ว_มหาวิทยาลัยเชียงใหม่_-_panoramio.jpg',why:'我想和你在这里慢一点。喝完咖啡以后，我们沿湖边走一圈，看素贴山压在水面后面，不需要再赶一个“著名景点”。',story:'安娇湖是清迈大学校园内的蓄水与休闲空间。今天它被学生和市民用来散步、慢跑与看山，也是理解校园贴着山脚生长的最好位置之一。',lookFor:['先站在湖的东侧看素贴山和水面的关系','沿步道观察学生跑步、休息和日常使用方式','傍晚云层厚时看山的轮廓，不执着日落'],together:'我们把它放在 17:00 左右。走完再去宁曼吃饭，整段都在同一小圈。',rain:'阵雨可以在附近室内等。连续下就改 CMU Art Center 或宁曼，湖边不用硬走。',current:['CMU Super App 页面目前写每日 06:00–22:00','校园临时分流或访客接驳以现场要求为准'],sources:[src('Chiang Mai University · Ang Kaew','https://superapp.camt.cmu.ac.th/places/ang-kaew')]},
  'one-nimman':{why:'这不是我想专门逛的商场，只是让我们在湖边之后不用再研究跨城晚饭。碰上周末 Street Food Market 才把它当宁曼夜市，平日就只是吃饭和散步。',story:'宁曼片区把咖啡、餐馆、设计店和夜间活动集中在步行尺度里，One Nimman 是一个好认的落点。市集属于活动，不应被写成每天固定存在。',lookFor:['先看官方当周活动页，不为一个已经结束的市集绕路','从主路拐进小巷后店铺密度的变化','晚饭前先看哪家真的有人在吃'],together:'安娇湖或山寺后回到这里。周末活动合适就逛，平日直接吃饭。',rain:'是西侧最方便的雨天收尾之一。',current:['商场官网目前写每日 11:00–21:00，夜间区域到 22:00','官方活动页曾列周末 Street Food Market 15:00–22:00，具体周次仍要复查'],sources:[src('One Nimman · 官方活动页','https://www.onenimman.com/event/'),src('One Nimman · Street Food Market','https://www.onenimman.com/en/event/66/')]},
  'sukhothai-mahathat':{imageFile:'Sukhothai, Wat Mahathat, Thailand.jpg',why:'素可泰值得多这一晚，关键就在这里。我们不在正午完成遗址清单，傍晚骑进中央区，让水面、草地和砖塔自己把节奏放慢。',story:'素可泰在 13 至 15 世纪成为重要都城。UNESCO 把这里与 Si Satchanalai、Kamphaeng Phet 作为连续遗产理解，强调早期泰国建筑语言、佛教艺术和复杂水利系统。玛哈泰寺是王城宗教核心。',lookFor:['莲花苞式主塔与周围小塔的层级','步行佛、坐佛和残存柱列之间的视线','池塘、堤岸与寺院并置，说明遗址不只有建筑'],together:'我们先租车或自行车，16:30 左右进入中央区。第一晚只看这里和沙西寺，天黑就回。',rain:'短雨后砖色会更深，但积水、雷雨或骑行视线差时不勉强。',current:['历史公园分区时段和票务临近出发向泰国艺术厅复核'],sources:[src('UNESCO · Historic Town of Sukhothai','https://whc.unesco.org/en/list/574/','世界遗产'),src('Fine Arts Department · Sukhothai Historical Park','https://www.qrcode.finearts.go.th/index.php/th/historicalpark/sukhothai/sukhothai-05'),lp]},
  'wat-sa-si':{imageFile:'Sukhothai - Wat Sa Si seen across the lotus pond Jan 2024.jpg',why:'它在水中小岛上，位置比建筑本身更重要。我想把它放在日落前，看佛塔、行走佛和水面慢慢变成同一种颜色。',story:'寺院位于 Traphang Tra Kuan 水池中，锡兰式钟形佛塔和素可泰行走佛让这里与玛哈泰寺的轴线感不同。',lookFor:['过桥前先从水对岸看完整轮廓','行走佛身体重心和手势','钟形佛塔与莲花苞式主塔的差别'],together:'从玛哈泰寺骑来很近。天色够就停，雨势大就回，不另赶外围。',rain:'桥面和草地湿滑时不等日落。',sources:[src('UNESCO · Sukhothai','https://whc.unesco.org/en/list/574/','世界遗产'),lp]},
  'wat-si-chum':{imageFile:'Wat Si Chum Sukhothai Thailand.jpg',why:'第二天早上来这里，是为了让素可泰不只剩远看的佛塔。狭窄佛殿和巨大坐佛会把人的尺度突然压小。',story:'Phra Achana 坐佛被围在高大的 mondop 中，顶部开放，光线从上方落下。遗址与石刻、地方传说都有联系，现场不要把传奇当成确证。',lookFor:['先在入口看手指和脸如何被墙框住','走近观察佛手表面的金箔','抬头看开口如何让自然光落到佛像上'],together:'清晨从中央区骑或叫车来。看完回入口附近吃东西、休息，再去机场。',rain:'佛殿能挡短雨，外围路面和骑行仍受影响。',sources:[src('UNESCO · Sukhothai','https://whc.unesco.org/en/list/574/','世界遗产'),lp]},
  'grand-palace':{imageFile:'A roof of a building at the Grand Palace, Bangkok, sunrise, 2017.jpg',why:'第一次到曼谷，我还是想和你把王城看清楚。我们早一点进去，不追求每栋楼都读完，先看权力、宗教和装饰怎样挤在同一片院落里。',story:'大皇宫自 18 世纪末成为暹罗王权核心，玉佛寺位于宫墙之内。建筑群持续增建，今天看到的是多个时期、不同用途与装饰系统叠加的结果。',lookFor:['玉佛寺回廊的 Ramakien 壁画和修复痕迹','金色佛塔、藏经阁与王室建筑屋顶的轮廓差别','礼仪空间如何用墙、门和平台控制移动'],together:'我们 08:30 前到。看两小时左右就出来，走去卧佛寺吃饭和休息。',rain:'短雨有回廊可避，暴雨会让院落移动很累。王宫当天若因王室活动调整，以官方日历为准。',current:['官网目前写 08:30–16:30，售票至 15:30','外国游客票目前 500 THB','覆盖肩膝，按入口安检和着装要求执行'],sources:[src('The Grand Palace · Visitor information','https://www.royalgrandpalace.th/en/contact'),src('The Grand Palace · Official ticket','https://www.royalgrandpalace.th/en/buy-ticket'),lp]},
  'wat-pho':{imageFile:'Wat Pho, Bangkok, Tailandia, 2013-08-22, DD 07.jpg',why:'王宫之后来这里，重点不只是卧佛。我们可以从巨大身体的尺度，走到院落里密集的佛塔，再看到寺院与传统医药教育的关系。',story:'Wat Pho 是曼谷最重要的皇家寺院之一，现有建筑与 Rama I 以来的扩建有关。寺院也以传统医药、按摩知识与碑刻传承闻名。',lookFor:['从脚底端看卧佛的尺度和螺钿纹样','院落里彩色小塔群的重复与差异','壁面知识图像如何把寺院变成学习空间'],together:'从大皇宫南侧步行过来。中午在附近休息，体力恢复后再过河。',rain:'主体建筑可避雨，院落之间仍暴露。按摩若想体验，先看官方现场安排。',current:['官网主页目前写 08:00–19:30、外国游客 300 THB；联络页出现 08:30 的差异，出发前再次核对','覆盖肩膝，遵守殿内拍摄提示'],sources:[src('Wat Pho · Official website','https://www.watpho.com/en/home'),src('Wat Pho · Plan your visit','https://www.watpho.com/en/contact/plan'),lp]},
  'wat-arun':{imageFile:'Templo Wat Arun, Bangkok, Tailandia, 2013-08-22, DD 30.jpg',why:'隔着河看它是一张曼谷明信片，坐船过去以后才会看见高塔表面其实由瓷片、贝壳和细小图案组成。这个远近变化值得。',story:'寺院可追溯至阿瑜陀耶时期，在吞武里成为王家寺院，主塔在 Rama II 与 Rama III 时期形成今天的主要规模。瓷片与贝壳镶嵌让它在不同光线下呈现不同质感。',lookFor:['从 Tha Tien 码头先看河对岸的完整轮廓','靠近后找瓷片、贝壳和 Benjarong 图案','留意陡阶和游客动线，不为照片逆行'],together:'我们从卧佛寺附近过河。下午热就先喝点东西，花市可以删。',rain:'塔阶湿滑时不上高处。雷雨时缩短河边和摆渡段。',sources:[src('TAT · Wat Arun','https://www.tourismthailand.org/Attraction/wat-arun-ratchawararam-ratchawaramahawihan'),src('TAT · Bangkok temples','https://www.tourismthailand.org/Articles/top-5-must-visit-temples-in-bangkok-once-in-a-lifetime'),lp]},
  'flower-market':{imageFile:'Bangkok Pak Khlong Talat 2.jpg',why:'如果我们从郑王庙回来还有精神，就去看城市怎样在傍晚处理成捆的花。累了就直接回去，没有遗憾。',story:'Pak Khlong Talat 是曼谷重要的花卉与农产品交易区。它的价值在工作节奏和街巷使用，不是单一建筑。',lookFor:['花束从批发包装到零售小串的变化','推车、摊位和道路如何分享狭窄空间','尊重工作中的商贩，拍近景先示意'],together:'从 Tha Tien 一带步行或叫车过去。只留半小时到一小时。',rain:'棚内可走，路口积水和车流会更麻烦。',sources:[lp]},
  'talat-noi':{imageFile:'Talat Noi Street Art.jpg',why:'我想让曼谷不只剩王宫和商场。这里有修车铺、宗祠、老宅和新咖啡店挤在一起，变化并不整齐，反而好看。',story:'Talat Noi 靠河发展，华人商业、仓储、修车与宗教空间长期叠加。Lonely Planet 把它列为适合步行与街头观察的老社区。',lookFor:['汽车零件和油污怎样占用店铺正面','So Heng Tai 等老宅与新店之间的距离','宗祠、教堂和河岸说明这里不只有一种移民历史'],together:'我们下午才来，从巷子慢慢走到 Yaowarat。不要为了每幅街头画绕路。',rain:'阵雨时找咖啡馆或屋檐。暴雨会让小巷积水，直接坐车去 Yaowarat 或回酒店。',sources:[lp,src('TAT · Bangkok overview','https://www.tourismthailand.org/Destinations/Provinces/Bangkok/219')]},
  'wat-traimit':{imageFile:'2016 Bangkok, Dystrykt Samphanthawong, Wat Traimit Witthayaram (08).jpg',why:'如果下午来得及，我们从金佛寺开始，让唐人街先有一段历史线索。赶不上闭馆也没关系，街区本身才是今晚主角。',story:'寺内金佛以材质、尺度和重新发现的故事著称。关于发现经过有多种叙述，现场解说与官方材料优先。',lookFor:['佛像表面金色与殿内光线','展陈如何解释金佛被灰泥覆盖的历史','从高处看华蓬与 Yaowarat 的城市关系'],together:'看完步行进入 Talat Noi。闭馆就直接从老街开始。',rain:'寺内可避雨，台阶湿时放慢。',sources:[lp]},
  'yaowarat':{imageFile:'2016 Bangkok, Dystrykt Samphanthawong, Ulica Yaowarat (05).jpg',why:'今晚不列十家必吃。我们从街头慢慢走，每站分一两样，喜欢就加，不喜欢就换。',story:'Yaowarat 是曼谷华人商业与餐饮主轴，白天的金铺、药材与批发，入夜后又被摊位和霓虹重新占用。',lookFor:['傍晚店面从白天生意切换到夜市的过程','同一种粿条或炭烤在不同摊位的做法','排队过长时看隔壁本地客流，不追唯一店名'],together:'我们从 Talat Noi 走来，吃到七八分饱就停。回程用 MRT Wat Mangkon 或 Grab。',rain:'中雨仍可在骑楼和店内移动，暴雨时直接选一家坐下吃。',sources:[lp]},
  'jim-thompson':{imageFile:'JT House - Jim Thompson House, Bangkok - Thailand - panoramio.jpg',why:'这不是只在雨天才去的备胎。六座木屋、收藏和一个人的复杂经历，正好让我们从王城转到 20 世纪曼谷。',story:'Jim Thompson 将多座传统泰式木屋重组为住宅与收藏空间，并推动泰丝国际传播。他 1967 年失踪，相关猜测很多，不能把传闻写成结论。',lookFor:['木屋抬高、通风和门槛的做法','不同房屋被重新组合后哪里仍能看出原结构','收藏品如何被放进居住空间，而非白盒展厅'],together:'我们预约或现场买票后跟官方导览，不另塞很多购物。下午步行或一站交通去 BACC。',rain:'适合雨天，但庭院、木阶和无电梯仍要考虑。',current:['官网目前写每日 10:00–17:00，最后导览 17:00','参观必须跟官方导览，可选中文','成人目前 250 THB，只在现场售票','超过 20 厘米的包需寄存，楼梯无电梯'],sources:[src('Jim Thompson House · Visitor information','https://jimthompsonhouse.org/visitor-information/'),lp]},
  'bacc':{imageFile:'BKK Art and Culture Centre.jpg',why:'如果曼谷下雨，我希望我们有一个真的能待住的地方，不是把下午全交给商场。展览看累了再过天桥去吃饭。',story:'BACC 是曼谷市中心的公共当代艺术空间，环形动线连接展厅、书店与小型文化空间。展览不断更换，背景应以当期项目为准。',lookFor:['先看一层当日展览表，不必逐层打卡','螺旋上升的公共空间如何组织视线','免费展与需登记项目分开确认'],together:'Jim Thompson 后过来最顺。我们挑一两个展，不为“逛完”走到闭馆。',rain:'完整室内线，周一闭馆是最重要的限制。',current:['官网目前写周二至周日 10:00–20:00、免费入场、周一闭馆'],sources:[src('Bangkok Art and Culture Centre','https://www.bacc.or.th/en')]},
  'benjakitti':{why:'晴天的话，我们把现代曼谷这天留一段给湿地和高架步道。它会让高楼之间的空间突然松开。',story:'公园由原烟草工厂区域逐步转型，水体、湿地与高架步行系统兼顾休闲和城市生态。',lookFor:['高架步道与地面湿地的两种视角','旧工业建筑保留的尺度','傍晚高楼倒影与水鸟活动'],together:'从 Siam 一带坐 MRT 或 Grab 过去。云层太厚或已经累，就不去。',rain:'雷雨时不走高架与开阔水边。',sources:[src('TAT · Bangkok overview','https://www.tourismthailand.org/Destinations/Provinces/Bangkok/219')]},
  'chatuchak':{imageFile:'Chatuchak Weekend Market 2.jpg',why:'只有日期正好落在周末、我们也想逛市场时才去。早上进，买到喜欢的就停，下午不在闷热里硬撑。',story:'Chatuchak 由大量分区与独立摊位组成，周末是最完整的零售时段。开放与摊位状态随周几差异很大。',lookFor:['进门先记入口和分区编号','把目标限制在两三类，别沿每条巷子扫完','补水、空调和集合点比“最佳路线”更重要'],together:'09:00 左右到，中午去对面的 Or Tor Kor 吃饭，14:00 前离开。',rain:'有顶但闷热、积水和人流仍会影响体验。暴雨时改 BACC。',current:['市场网站目前写周六、周日 09:00–18:00 为完整周末市场；临近再核'],sources:[src('Chatuchak Market · Opening times','https://www.chatuchakmarket.org/opening-times/')]},
  'or-tor-kor':{why:'逛完 Chatuchak，我们不继续在摊位里找午饭，过街来这里坐下、吃水果，把节奏稳住。',story:'这是以农产、熟食和水果见长的市场，环境比大型周末市场更易辨认。',lookFor:['先绕一小圈再决定吃什么','两个人分着试当季水果','价格和份量先问清楚'],together:'只在周末市场模块里出现，午饭后回 Siam。',rain:'主体有顶，过街和接驳时注意积水。',sources:[src('Or Tor Kor · Google Maps 实时信息','https://www.google.com/maps/search/?api=1&query=Or+Tor+Kor+Market+Bangkok','现场复核')]},
  'elephant-nature-park':{imageFile:"Elephant d'Asie (Elephant nature park, Thaïlande).jpg",why:'如果我们只选一个清迈远郊体验，我更愿意把时间留给观察被救助的大象怎样自己走动、进食和结群。互动越少，通常越接近它们的需要。',story:'Elephant Nature Park 位于湄登，是救助与庇护园区。大象旅游里“能触摸”不等于更善待动物，骑乘、表演、强迫洗澡和贴身自拍都可能依赖长期控制。',lookFor:['先看象群之间的距离、跟随与让路','观察耳朵、鼻子和身体朝向，不追着靠近','听工作人员解释每头象的救助背景，同时把宣传与可见行为分开'],together:'提前预订含市区接送的全日或 SkyWalk 项目。常见接人约 07:30–08:30，傍晚回城；回来后只吃饭，不再叠夜间动物园。',rain:'园区多为户外。连续强降雨或湄登洪水风险出现时听从园方取消安排；2024 年 10 月园区曾遭严重洪水，不能把雨季当普通小雨。',current:['只选不骑乘、不表演、不洗象、不触摸的观察型项目','官网列有半日、全日与 SkyWalk 等项目，库存与接送范围以预订页为准'],sources:[src('Elephant Nature Park · Visit','https://www.elephantnaturepark.org/enp/visit-'),src('Elephant Nature Park · SkyWalk','https://elephantnaturepark.org/visit-volunteer/skywalk/'),src('World Animal Protection · elephant experiences to avoid','https://www.worldanimalprotection.org.uk/latest/blogs/elephant-experiences-to-avoid/','动物福利')]},
  'night-safari':{imageFile:'Deer Chiang Mai Night Safari.jpg',why:'夜间电车会带来与寺庙、咖啡完全不同的夜晚，但它是动物园体验，不会和大象保护区混写成“同一种亲近动物”。只有我们真的想去才打开。',story:'园区位于清迈西南郊，分步行区与电车区。动物活跃程度、表演和喂食安排会随季节与园方调整。',lookFor:['先走一小段步行区，再把时间留给较早班电车','不使用闪光灯，不敲玻璃或呼喊吸引动物','如果某项互动让动物被迫靠近，直接跳过'],together:'从市区叫车约 35–45 分钟，建议 16:30–17:00 抵达，搭较早的夜间电车。它替换安娇湖与宁曼夜晚，不放在大象日之后。',rain:'短雨时电车仍可能运行，雷暴和强雨会影响步行、视线与演出；出发前看园方当天通知。',current:['官网目前写园区 11:00–22:00，售票处约 21:00 截止','夜间电车通常约 17:30–21:00 每 30 分钟一班，全程约 60 分钟'],sources:[src('Chiang Mai Night Safari · Visit','https://chiangmainightsafari.com/en/visit/'),src('Chiang Mai Night Safari · Night tram','https://chiangmainightsafari.com/en/ticket/night-safari/')]},
  'jing-jai':{why:'周六或周日早上，我会在 JJ 和 Nong Ho 里先选 JJ。这里更适合两个人边吃早餐边看农产、手作和本地设计，逛完还能从容去机场。',story:'Jing Jai 的常设商业空间每天开放，真正让它值得专门来的 Farmers Market 与 Rustic Market 集中在周末早晨。',lookFor:['先吃早餐，再看农产与手作，不从纪念品区开始扫','带可重复使用的袋子和少量现金','十一点左右看体力，别为了逛完拖到赶飞机'],together:'如果飞曼谷那天是周六或周日，06:30–10:30 来，回酒店取行李后去机场。非周末不把常设商场冒充成同一场市集。',rain:'部分区域有顶，摊位与通道仍受大雨影响。暴雨时直接睡够、去机场。',current:['官网写周末 Farmers Market 与 Rustic Market 为周六、周日 06:30–15:00','常设市场每天开放，但体验与周末早市不同'],sources:[src('Jing Jai Central · Market','https://www.jingjaicentralchiangmai.com/market')]},
  'nong-ho':{why:'如果我们想翻旧衣、家具、唱片和杂物，而不是逛更整洁的农夫与手作市集，就用它替换 JJ。两处都跑只会把一个早晨变成采购任务。',story:'这里更接近 car-boot flea market，摊主从车上卸下二手物与小型手作。摊位品质参差正是体验的一部分。',lookFor:['先绕一圈再买，旧物状态当面检查','备现金，也给行李体积设上限','把烈日和泥地当实际条件，不期待精致布景'],together:'只在周末早晨安排，建议 07:00 左右到。因为营业资料没有稳定官方页面，前一晚还要在地图和社交页面确认。',rain:'露天与临时棚架多，持续降雨就换 JJ 的有顶区域或直接取消。',current:['Time Out 2026 年 6 月资料写周末 07:00–14:00','第三方目录时间不一致，属于需要临场复核的低置信度点'],sources:[src('Time Out Chiang Mai · Nong Ho Flea Market','https://www.timeout.com/chiang-mai/shopping/nong-ho-flea-market','近期编辑推荐')]},
  'lila-oldcity':{why:'寺庙和市场走完以后，我们可以停下来做一次真正留有时间的泰式按摩，不把它塞到临睡前最后一小时。',story:'Lila 由清迈女子监狱前管理者推动，为接受过按摩训练的前女性服刑人员提供就业机会。不同分店项目与技师排班会变。',lookFor:['第一次可以选 60–90 分钟泰式或精油项目','提前说明旧伤、力度和不希望触碰的位置','结束后补水，不立刻喝很多酒'],together:'放在老城日 17:00 左右最顺。若当晚还去爵士现场，就先吃一顿清淡晚饭；预约不上则换 Fah Lanna，不跨区追店。',rain:'完整室内安排，是持续下雨时很自然的替换。',current:['官网目前写每日 10:00–22:00','热门时段建议提前预约'],sources:[src('Lila Thai Massage · Official','https://www.lilathaimassage.com/')]},
  'after-khok-wua':{why:'你找到的 511 走法可以留着，但它只对住处恰好在 511 走廊上的那天省事。否则先坐 MRT 到 Sanam Chai，再步行或短程打车，通常更稳。',story:'After Khok Wua 位于 Ratchadamnoen Klang 一带，靠近民主纪念碑与考山路。它是公交站，不是王宫入口。',lookFor:['上车前用实时公交应用确认方向与车辆位置','下车后按实时步行导航过路，不背固定“左转右转”口令','给大路口和人行横道留时间'],together:'如果酒店附近能直接上 511，就在这里下车后步行约 15 分钟去大皇宫。否则当天地图从 MRT Sanam Chai 开始，不特意来这个站。',rain:'大雨时公交等候与步行都不舒服，改 MRT 加短程 Grab。',current:['511 当前为城市长线路，不能从曼谷任意位置直接乘坐','线路与站位会调整，必须以当天实时交通应用为准'],sources:[src('Bangkok bus 511 · current route data','https://transitbycity.com/th/thailand/krungthephmhankhr/operators/khsmk/routes/511/','实时路线参考')]},
  'tha-tien':{why:'卧佛寺到郑王庙真正省力的关键就是这几分钟摆渡。我们过河前先从码头看一次整座塔，再到对岸看瓷片细节。',story:'Tha Tien 是王城南侧重要码头与市场节点，连接 Rattanakosin 与吞武里。码头服务可能分为过河渡轮与沿河船。',lookFor:['入口牌上确认目的地为 Wat Arun 对岸','备零钱或按现场电子支付方式购票','高水位、雷雨或停航时不要硬等'],together:'从卧佛寺出口跟实时导航步行约 5–10 分钟，不依赖一段可能因施工改变的口头路线。',rain:'雷雨或临时停航时不坐船，改车去郑王庙或直接删掉。',sources:[src('Chao Phraya Express Boat · official','https://www.chaophrayaexpressboat.com/chaophrayaexpressboat?lang=en')]},
  'mama-cafe':{imageFile:'Wat Paknam Buddha.jpg',why:'这条不起眼的小巷能把大佛正面放进普通社区的尺度里。照片好看，但我们先确认店铺和巷口，不在居民门前反复摆拍。',story:'Wat Paknam 大佛完成后，周围住宅巷与咖啡馆形成一组新的城市观看点。它们不是官方观景台，营业与通行都可能变化。',lookFor:['导航核对 Mama Cafe Buddha Front 与 60–62 Phet Kasem 15 Lane 9','先消费或询问店员再拍摄，不占住通道','看大佛怎样从低层住宅后方升起'],together:'10:00 左右从这里开始，之后步行去 Wat Pradu 和水门寺。网上的 Mama Cooking 多半是误写。',rain:'巷道积水或店铺未开就直接跳过，水门寺本身才是主角。',current:['Wongnai 当前列出的地址为 60–62 Phet Kasem 15 Lane 9','当前页面列每日 10:00–18:00，临近仍要复查'],sources:[src('Wongnai · Mama Cafe Buddha Front','https://www.wongnai.com/restaurants/3572401yT-mama-cafe-buddha-front-thapra','商家目录'),src('Journey.tw · current photo route','https://journey.tw/mama-cafe/','近期游记')]},
  'wat-pradu':{why:'从这里可以把大佛与观音像放在同一个画面里，也让我们看见宏大新地标与小型社区寺院怎样挨在一起。',story:'Wat Pradu Chimphli 是吞武里一带仍在使用的佛教寺院。它作为取景点的流行晚于寺院本身，礼拜与社区使用优先于摄影。',lookFor:['先确认殿堂是否有仪式，再找不挡路的位置','观察两座佛像在不同距离下的比例','拍完把注意力放回寺院日常，而不只找同款机位'],together:'从 Mama Cafe 步行约 5–10 分钟，再继续走到 Wat Paknam。',rain:'大殿周边可避短雨，社区小路积水时叫车。',sources:[src('Apple Maps · Wat Pradu Chimphli','https://maps.apple.com/place?place-id=I8C20EA9DEFC4A282','地图资料')]},
  'wat-paknam':{imageFile:'Wat Paknam Buddha.jpg',why:'我会把这条线当吞武里半日，而不只是一张大佛照片。进寺以后还要看塔内玻璃佛塔、运河和社区屋顶怎么围住这座新地标。',story:'Wat Paknam 可追溯至阿瑜陀耶时期，是吞武里重要皇家寺院。近年建成的大型坐佛改变了这一带的天际线，塔内顶层的绿色玻璃佛塔也成为主要参观点。',lookFor:['从巷口、寺院入口与塔上分别比较大佛尺度','进入殿堂与佛塔时遵守着装、脱鞋和拍摄提示','把运河、学校与住宅一起看，别只仰拍佛像'],together:'午前从 Wat Pradu 走来，预留 60–90 分钟。之后只沿公共道路去桥位和 Talat Phlu，不钻没有标识的近路。',rain:'寺院室内可以接住阵雨，桥位和社区巷道在暴雨时直接删掉。',current:['网上开放时间存在 06:00–20:00 与 08:00–18:00 等差异','为避免扑空，计划在 17:00 前完成主体参观并在当天复核'],sources:[src('Visit Thailand Today · Wat Paknam','https://www.visitthailandtoday.com/temples-culture/bangkok/wat-paknam-phasi-charoen','当前访问信息'),src('TAT · Talat Phlu area','https://www.tourismthailand.org/Articles/talat-phlu')]},
  'wat-paknam-bridge':{imageFile:'Big Buddha at Wat Pak Nam Phasi Charoen Bangkok Thailand by Don Ramey Logan.jpg',why:'这里能看大佛背影和运河社区，但它只是公共桥位，不值得为了复刻一张照片去穿厕所出口、摊位后门或私人小巷。',story:'大佛出现以后，周围公共桥梁与巷道自然形成了多种取景角度。社交平台口令式路线可能忽略施工、私域和现场礼仪。',lookFor:['只沿地图上标示的公共道路与现场指示走','不要在桥面停太久或影响摩托与居民通行','水边护栏低、地面湿时收起手机慢走'],together:'从水门寺的正式出口出发，用实时步行导航到公共桥面。找不到就删，不向商贩后方硬闯。',rain:'下雨、天黑或水位异常时不去。',sources:[src('Journey.tw · Wat Paknam photo route','https://journey.tw/mama-cafe/','近期游记')]},
  'at-talat-phlu':{imageFile:'Wat Paknam Buddha.jpg',why:'走完寺院后，我们在这里坐下来，从露台看大佛退回吞武里屋顶后面。它更适合作为半日结束，而不是再加一串咖啡馆。',story:'Talat Phlu 是运河与铁路塑造的老社区，美食与市场传统早于大佛取景热。咖啡馆露台只是理解这一片屋顶尺度的一个位置。',lookFor:['点单前先问当天露台是否开放、是否有最低消费','二层与三层角度不同，不为机位翻越围挡','离开前在 Talat Phlu 附近吃一两样，不再跨城找饭'],together:'从公共桥位步行约 8–12 分钟。若当天关门，就直接去 Talat Phlu 市场与火车站周边。',rain:'露台在雨天失去意义，改在室内坐一会儿或直接返程。',current:['第三方当前目录写工作日 10:00–20:00、周末 12:00–20:00','露台规则和费用曾变化，出发当天必须再确认'],sources:[src('AT TALAT PHLU · current directory','https://www.thaithurkic.com/at-talat-phlu-095-252-3392','商家目录'),src('TAT · Talat Phlu','https://www.tourismthailand.org/Articles/talat-phlu')]},
  'wongwian-yai-srt':{imageFile:'Wongwian Yai Railway Station (I).jpg',why:'如果你想把“坐火车去美功”本身当旅行，这里就是第一站。它不是 BTS Wongwian Yai，两个站之间还要步行或短程接驳。',story:'美功铁路被 Tha Chin River 分成两段。东段从 Wongwian Yai 到 Mahachai，过河后才在 Ban Laem 接上西段。',lookFor:['前一晚核对 SRT 时刻，不把售票与上车留到最后一分钟','确认站牌写 Mahachai','带水和简单早餐，普通列车没有按城际服务期待的配置'],together:'06:55–07:10 到站买票，搭当前 07:40 班次，约 08:39 抵达 Mahachai。',rain:'强雨可能影响步行换乘与线路运行，出发前看 SRT 公告。',current:['SRT 当前时刻表列 07:40 从 Wongwian Yai 开、08:39 到 Mahachai','时刻可能改，不能只看页面截图'],sources:[src('State Railway of Thailand · line 5 timetable','https://ttsview.railway.co.th/timetable_modern.php?line=5&ln=en&trip=1','铁路官方')]},
  'mahachai-station':{why:'到这里不是同站换乘。我们要穿过市场、走到河边坐渡轮，这一段才是美功铁路特殊结构的一部分。',story:'Mahachai 是 Samut Sakhon 的市场与渔港城市，铁路东段在河东岸结束。',lookFor:['下车先确认渡轮方向，不跟着错误人流逛远','给市场拥挤和买票留至少 30 分钟','湿滑鱼市里看脚下，不拖大件行李'],together:'08:39 到站后步行约 10–15 分钟去 Mahachai Ferry，过河再走去 Ban Laem。',rain:'市场可遮一部分雨，渡轮与路面积水仍是变量。',sources:[src('State Railway of Thailand · line 5 timetable','https://ttsview.railway.co.th/timetable_modern.php?line=5&ln=en&trip=1','铁路官方')]},
  'mahachai-ferry':{why:'这段几分钟的渡轮连接两条彼此不相连的铁路。赶 10:10 火车时，它比拍照更重要。',story:'Tha Chin River 将 Mahachai 与 Tha Chalom 分开，渡轮承担本地日常通勤，也成为美功铁路旅程的必要接缝。',lookFor:['确认上船方向是 Tha Chalom','准备零钱并照看随身物品','下船后立即按步行导航去 Ban Laem'],together:'最晚尽量在 09:20 前过河，给去车站与找站台留余量。',rain:'雷雨、强风或停航时整条 DIY 铁路线要重算，不能靠冲刺补回。',sources:[src('Google Maps · Mahachai ferry','https://www.google.com/maps/search/?api=1&query=Mahachai+Ferry+Pier','地图复核')]},
  'ban-laem-station':{imageFile:'Ban Laem Railway Station.jpg',why:'这座小站是西段铁路起点。赶上 10:10，才会在 11:10 随列车一起进入美功市场。',story:'Ban Laem 站服务 Tha Chalom，与 Mahachai 隔河相望。它的慢速普通列车进入美功前会穿过盐田、社区与市场。',lookFor:['在站台再次确认列车终点 Mae Klong','早点上车选择舒服座位，但不占当地通勤空间','车窗伸手和探身都不安全'],together:'搭当前 10:10 班次，约 11:10 抵达 Mae Klong。错过后等待很久，当天不再硬追丹嫩。',rain:'列车服务变更以 SRT 为准。站内遮蔽有限，带轻便雨衣。',current:['SRT 当前时刻表列 10:10 发车、11:10 到 Mae Klong'],sources:[src('State Railway of Thailand · line 6 timetable','https://ttsview.railway.co.th/timetable_modern.php?line=6&ln=th&trip=1','铁路官方')]},
  'maeklong-market':{imageFile:'Maeklong Railway Market 04.jpg',why:'最有意思的不是站在轨道中央自拍，而是看摊主怎样在几分钟内把遮棚和货物让给一列日常火车。我们如果坐进场列车，视角会比等车更完整。',story:'市场沿美功铁路终点附近形成，铁路与生鲜交易共享极窄空间。列车来到时摊主收起棚布，驶过后市场迅速恢复。',lookFor:['只站在工作人员允许的区域，不把轨道当摄影棚','提前看摊主收棚的顺序与速度','车过后再看市场如何恢复交易'],together:'DIY 版随 11:10 列车进场；效率版则在 10:30 前到市场等待同一班车。看完 11:30 发车后吃饭、回曼谷。',rain:'雨会让遮棚、轨道与人流更混乱，听从工作人员指挥。',current:['SRT 当前列出到站 08:30、11:10、14:30、17:40，发车 06:20、09:00、11:30、15:30','临近日期必须再次核对'],sources:[src('State Railway of Thailand · line 6 timetable','https://ttsview.railway.co.th/timetable_modern.php?line=6&ln=th&trip=1','铁路官方'),src('Wikimedia Commons · current market photo','https://commons.wikimedia.org/wiki/File:Maeklong_Railway_Market_04.jpg','图像与坐标')]},
  'samutsongkhram-bus':{why:'用户攻略里把这里当去丹嫩和回曼谷的集散点是合理线索，但车站、面包车上客处与线路会移动，不能只记一个英文定位。',story:'美功市区的公路客运由巴士、面包车与当地双条车共同承担，现场组织不一定像大型车站那样固定。',lookFor:['先问清终点、发车时间和是否中途换车','回曼谷时确认到 Southern Bus Terminal 还是其他落点','上车前保存酒店泰文地址'],together:'效率版看完美功后从这里回曼谷；若去丹嫩，最好清晨包车先去，而不是中午才临时找突突车。',rain:'暴雨会拉长公路时间，返程给曼谷晚餐留弹性。',sources:[src('Google Maps · Samut Songkhram Bus Terminal','https://www.google.com/maps/search/?api=1&query=Samut+Songkhram+Bus+Terminal','现场复核')]},
  'damnoen-saduak':{imageFile:'Damnoen Saduak Floating Market (7996110037).jpg',why:'如果我们要去，我希望看到的是清晨船只与沿岸交易刚开始的状态，而不是中午抵达后为了“来过”再租一条观光船。',story:'Damnoen Saduak 运河在 19 世纪开凿，市场与果园、水路运输相连。今天旅游商业化很强，清晨和晚到的感受差别很大。',lookFor:['07:00–09:00 先沿岸观察，再决定是否坐船','船价、时长与路线在上船前写清楚','不把叫卖与议价拍成猎奇画面'],together:'两地同日的效率版要 06:00 左右从曼谷包车，07:15–08:45 在丹嫩，随后去美功等 11:10 列车。全火车版 11:10 才到美功，不再追加这里。',rain:'短雨仍可看，暴雨、雷电或水位异常时不坐小船。',current:['近期体验资料普遍建议 07:00–09:00 到达，接近中午活跃度明显下降','船价与上船点差异大，现场先确认'],sources:[src('TAT · Damnoen Saduak Floating Market','https://www.tourismthailand.org/Attraction/damnoen-saduak-floating-market'),src('The Better Vacation · current timing signal','https://thebettervacation.com/bangkok-city/damnoen-saduak-floating-market/','近期体验')]}
};

details['jok-prince']={why:'如果我们住在 Charoen Krung 一带，或者晚上还想吃一碗热的，就把这里当顺路停靠。它不值得从 Yaowarat 特意往南折返。',story:'Jok Prince 以炭火带来的烟熏感和绵密泰式粥出名。老店搬迁、营业时段与排队状态都可能变化，旧版书上的钟点不能直接照搬。',lookFor:['先看当天是堂食、外带还是需要排队取号','两个人先分一碗，再决定要不要加蛋或内脏','确认回酒店方向，别为了这一站把老城夜线拉长'],together:'它只在 Talat Noi 同方向或住得近时成立。我们的主线仍是旧巷到 Yaowarat。',rain:'大雨时可以坐下吃，但叫车上下客会受 Charoen Krung 路况影响。',sources:[src('Jok Prince · Google Maps 实时信息','https://www.google.com/maps/search/?api=1&query=Jok+Prince+Bangkok','现场复核'),lp]};
details['sukhothai-cafe']={why:'清晨骑完以后，我们需要冷气、冰饮和一个能慢慢等车的地方。它是休息点，营业状态不稳就换历史公园入口附近的店。',story:'Cafe Thammada 常被旅行者当作历史公园附近的艺术咖啡馆。它不是遗产本体，装潢、菜单和营业安排都可能变化。',lookFor:['先看当天营业和座位，不把行李留在无人照看的位置','两个人补水、简单吃一点，给下午接驳留体力','返程前确认从店到酒店和机场车的时间'],together:'西春寺后回到中央区，吃午饭、喝咖啡、取行李。15:00 左右开始为机场接驳留余量。',rain:'适合等短雨。若暴雨影响道路，先让酒店确认机场车，咖啡可以删。',sources:[src('Cafe Thammada · Google Maps 实时信息','https://www.google.com/maps/search/?api=1&query=Cafe+Thammada+Sukhothai','现场复核')]};
details['ths']={imageFile:'Sukhothai Airport Passenger Terminal.jpg',why:'这座小机场决定了素可泰能不能成为开口路线。我们从这里飞曼谷，省掉返回清迈或再坐六七小时公路车。',story:'Sukhothai Airport 由 Bangkok Airways 运营，班次少，机场本身也采用低层、开放式的度假建筑语言。真正要紧的是最终航班是否仍在售。',lookFor:['订票时确认机场代码 THS 和落地机场 BKK','让酒店或车行写明接人时间，不靠路边临时叫车','进机场后再看柜台与安检时间，小机场也不能按最后一分钟到'],together:'上午骑行后回酒店休息。我们预留 35–45 分钟车程，并在航班要求的值机截止前到达。',rain:'大雨时更早离开历史公园。航班变更以航空公司通知为准。',current:['班次与票价波动大，先出票再锁素可泰不可退住宿'],sources:[src('Bangkok Airways · Sukhothai to Bangkok','https://www.bangkokair.com/flightdeals/view/sukhothai-bangkok','航空公司')]};
details['mahanakhon']={why:'只有天空够清、我们也还想看高处时才去。低云和雷雨会把高价观景台变成一段没有远景的室内电梯。',story:'Mahanakhon 的像素化退台让它成为曼谷当代天际线标志，顶部观景设施与天气关系很大。票种和入场时段经常变化。',lookFor:['买票前先看实时云层和雷达','从高处辨认湄南河、Silom 与远处王城方向','玻璃步道按现场鞋套、拍摄和雷雨关闭要求执行'],together:'它只替代公园的傍晚，不和 Benjakitti 同时硬塞。',rain:'雷雨、低云或能见度差时整段取消，不提前买难退票。',sources:[src('King Power Mahanakhon · 官方网站','https://kingpowermahanakhon.co.th/') ]};
details['doi-inthanon']={imageFile:'Doi Inthanon, Royal Chedi, Thailand.jpg',why:'如果你更想看雨季山林，我们可以拿清迈慢日换这一整天。它离城远，只有天气窗口清楚、我们愿意早起时才成立。',story:'茵他侬海拔 2565 米，是泰国最高峰。高地森林、Ang Ka 步道、王室佛塔和瀑布分散在公园道路两侧，需要车辆组织。',lookFor:['峰顶林地里苔藓、附生植物与低海拔植被的差别','Ang Ka 木栈道在浓雾里的能见度和湿滑程度','王室佛塔观景是否被云层遮住'],together:'这是一整天包车线路，不能和老城或宁曼半日叠加。',rain:'雨季能见度不保证。暴雨、落石或公园警报出现就取消，Kew Mae Pan 是否开放也要单独确认。',sources:[src('TAT · Doi Inthanon','https://www.tourismthailand.org/Articles/mountain-savouring-the-greens-at-doi-inthanon')]};
details['wachirathan']={imageFile:'Wachirathan Waterfall 1.jpg',why:'雨季水量会很好，但这里只是茵他侬日的一站。我们看水势、拍几张就走，不在飞沫和湿石上久留。',story:'Wachirathan 是茵他侬公园道路旁最容易到达的大瀑布之一，雨季水雾会覆盖观景区域。',lookFor:['先看观景台地面是否被水雾打湿','手机和相机先装进防水袋再靠近','不越过护栏找角度'],together:'把它放在峰顶与回城之间，由司机按雨势决定先后。',rain:'暴雨或雷声出现时不靠近瀑布，直接离开。',sources:[src('TAT · Doi Inthanon waterfalls','https://www.tourismthailand.org/Articles/mountain-savouring-the-greens-at-doi-inthanon')]};
details['white-temple']={imageFile:'Wat Rong Khun-001.jpg',why:'如果我们选清莱，就是为了这种和古都遗址完全不同的当代宗教建筑。白庙由一位艺术家持续推进，细节比远看的白色轮廓更重要。',story:'Wat Rong Khun 由艺术家 Chalermchai Kositpipat 设计并持续建造，把佛教图像、当代文化和强烈个人风格放在同一套白色建筑里。',lookFor:['入口桥下手臂与欲望主题如何引导进入','镜片与白色灰泥怎样改变阳光反射','当代流行图像出现在哪里，又怎样与传统叙事并置'],together:'08:00 左右先到城南白庙，再由包车向北走。',rain:'雨天反光较柔，但雷雨时开放空间和桥面都不舒服。',sources:[src('TAT · Chiang Rai overview','https://www.tourismthailand.org/Destinations/Provinces/Chiang-Rai/102'),lp]};
details['blue-temple']={imageFile:'Wat Rong Suea Ten (Blue Temple, Chiang Rai) วัดร่องเสือเต้น (October 2021) - img 01.jpg',why:'抵达清莱后的下午先看蓝庙，能用一小时确认我们是否喜欢这条当代建筑分支。',story:'蓝庙由本地艺术家 Puttha Kabkaew 参与设计，以蓝金对比、那伽与大型白佛形成强烈视觉。',lookFor:['山门那伽的蓝金层次','主殿壁画与白佛之间的色彩关系','傍晚室外灯光亮起前后的变化'],together:'从汽车站或酒店叫车过去，晚上回钟楼一带吃饭。',rain:'主殿可避雨，入口台阶和外部雕塑区仍会湿。',sources:[src('TAT · Wat Rong Suea Ten','https://www.tourismthailand.org/Articles/https-www-tourismthailand-org-articles-4must-seeplacesinchiangrai')]};
details['baan-dam']={imageFile:'Baan Dam.jpg',why:'白庙之后来看黑屋，颜色反差很直接，背后也有两位泰北艺术家对传统材料的不同处理。',story:'Baan Dam 是艺术家 Thawan Duchanee 创建的建筑与艺术集合，多座深色木构空间陈列动物材料、器物和作品。',lookFor:['不同黑色建筑并非一座连续博物馆','木构、角、皮革与金属材料怎样被并置','哪些空间允许进入，哪些只能从外部看'],together:'包车从城南一路到城北，结束后直接去 CEI，不回市中心折返。',rain:'建筑之间是户外庭院，持续大雨会明显削弱体验。',sources:[src('TAT · Chiang Rai overview','https://www.tourismthailand.org/Destinations/Provinces/Chiang-Rai/102'),src('TAT · Chiang Rai transport route','https://www.tourismthailand.org/Articles/chiang-rai-chiang-mai-a-great-low-budgeted-trip'),lp]};
details['clock-tower']={imageFile:'Chiang Rai - Clock Tower - 0001.jpg',why:'它只是清莱住一晚的好认落点。我们在附近吃饭、看一眼灯光就回去，不为整点表演守很久。',story:'金色钟楼由 Chalermchai Kositpipat 设计，延续了白庙的装饰语言，也把交通环岛变成城市舞台。',lookFor:['白天金色细部与夜间灯光的差别','环岛车流很快，拍照不要站进车道','表演时间临近再看现场公告'],together:'住钟楼或夜市周边，蓝庙回来后步行吃饭。',rain:'大雨时从餐馆或酒店远看，不站路口等。',sources:[src('TAT · Chiang Rai overview','https://www.tourismthailand.org/Destinations/Provinces/Chiang-Rai/102')]};
details['cei']={why:'清莱线最后从 CEI 直飞曼谷，省掉回清迈的三小时公路。路线能不能成立，要先看最终日期有没有合适航班。',story:'Mae Fah Luang–Chiang Rai International Airport 位于市区北侧，是清莱路线的航空出口。',lookFor:['订票时确认 CEI 与曼谷落地机场','包车从黑屋直接去机场，预留堵车和还车时间','进航站楼后先看柜台与登机口，不按小机场做最后一分钟计划'],together:'白庙、黑屋和机场在南北一条轴上，包车全日最顺。',rain:'大雨时提前离开黑屋，航班变化以航空公司为准。',sources:[src('TAT · Chiang Rai getting there','https://www.tourismthailand.org/Destinations/Provinces/Chiang-Rai/102')]};
details['wat-phan-tao'].imageFile='Chiang Mai - Wat Phan Tao - 0001.jpg';
details['monks-trail'].imageFile='Doi Suthep Monk Trail 1.jpg';
details['one-nimman'].imageFile='One Nimman.jpg';
details['benjakitti'].imageFile='Benjakitti Forest Park (I).jpg';
Object.entries(details).forEach(([id,extra])=>Object.assign(places.find(x=>x.id===id)||{},extra));
const p=id=>places.find(x=>x.id===id);
const localDate=s=>new Date(`${s}T12:00:00`);
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const zhDate=d=>`${d.getMonth()+1}月${d.getDate()}日`;
const week=d=>['周日','周一','周二','周三','周四','周五','周六'][d.getDay()];
const add=(d,n)=>new Date(d.getTime()+n*DAY);
const commonsImage=file=>file?`https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(file)}?width=1000`:'';
const commonsPage=file=>file?`https://commons.wikimedia.org/wiki/File:${encodeURIComponent(file.replaceAll(' ','_'))}`:'';
const mapsSearch=place=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${place.name} Thailand`)}`;
const mapsRoute=(a,b,mode='walking')=>`https://www.google.com/maps/dir/?api=1&origin=${a.lat},${a.lng}&destination=${b.lat},${b.lng}&travelmode=${mode}`;

const dayDefs={
  arrival:{title:'晚上抵达清迈，我们只管安顿好',tag:'核心',area:'机场到酒店，没有固定游览圈',summary:'第一晚不拿航班准点去赌预订。我们放好行李，在住处附近吃一顿，然后早点睡。',slots:['晚间｜机场→酒店→附近吃饭','住哪里｜老城东侧或宁曼，清迈段不换酒店','如果早到｜只散步，远处留给明天'],ids:[]},
  cmOld:{title:'清迈老城只留两座寺庙，晚上去按摩',tag:'核心',area:'老城西侧到河边市场，再回老城收尾',summary:'我把潘道寺和连续寺庙都拿掉。上午只看帕辛寺与契迪龙寺，下午选市场或博物馆，傍晚留足一次按摩的时间。',slots:['08:30｜帕辛寺→契迪龙寺，到这里停寺庙','14:30｜Warorot；下大雨就换兰纳民俗馆','17:30｜Lila 按摩；有精神再听爵士'],ids:['wat-phra-singh','wat-chedi-luang','warorot','lila-oldcity'],segments:[['步行','12–18 分'],['双条车 / Grab','10–20 分'],['Grab / 双条车','10–18 分']],alternatives:[{id:'lanna-museum',label:'持续下雨时换这里'},{id:'north-gate-jazz',label:'按摩后仍有精神再去'}]},
  cmElephant:{title:'把一天留给大象，但不靠触摸获得体验',tag:'核心',area:'清迈市区往返湄登，约 60 公里远郊',summary:'我们只订不骑乘、不表演、不洗象、不贴身自拍的观察型项目。接送通常占掉早晚，这天不再叠夜间动物园。',slots:['07:30–08:30｜园方按范围接酒店','白天｜远距离观察、步行和园区说明','约 17:30｜回城，晚饭后休息'],ids:['elephant-nature-park'],choiceNote:'项目名字里写 sanctuary 还不够。真正要看的，是有没有骑乘、洗象、表演与强迫接触。'},
  cmWest:{title:'山寺之后，回清迈大学附近喝咖啡',tag:'核心',area:'素贴山到清迈大学、安娇湖与宁曼西侧',summary:'今天只留帕拉寺和双龙寺两座山寺。下午回大学附近喝咖啡，傍晚绕安娇湖，再到宁曼吃饭。',slots:['08:30｜包红车去 Wat Pha Lat→双龙寺','14:30｜Ristr8to，排队太长就换附近店','17:00｜安娇湖→宁曼；周末再看市集'],ids:['wat-pha-lat','doi-suthep','ristr8to','ang-kaew','one-nimman'],segments:[['包红车','20–30 分'],['包红车下山','35–50 分'],['步行 / Grab','8–15 分'],['步行 / Grab','10–15 分']],alternatives:[{id:'monks-trail',label:'前夜没下雨才用徒步替换上山车'}]},
  cmSlowNight:{title:'艺术村只来一次，晚上再决定要不要看夜间动物园',tag:'可换',area:'城西手作社区与艺术中心，夜间向西南远郊',summary:'Baan Kang Wat 只放在今天，不再重复。下午看展或回酒店休息；若我们选 Night Safari，就拿掉安娇湖与宁曼夜晚。',slots:['10:30｜Baan Kang Wat 慢慢逛','14:00｜CMU Art Center / 回酒店午休','16:30｜Night Safari；不想去就留在宁曼'],ids:['baan-kang-wat','cmu-art-center','night-safari'],segments:[['Grab / 步行','8–15 分'],['Grab','35–45 分']],alternatives:[{id:'one-nimman',label:'不去动物园就回宁曼吃饭'},{id:'ang-kaew',label:'不去动物园就看湖边傍晚'}],choiceNote:'夜间动物园和湖边夜晚二选一。大象日回来后不要再赶这里。'},
  cmFlex:{title:'清迈机动日，天气好才进山',tag:'可换',area:'茵他侬山区，跨城远郊模块',summary:'若我们特别想看雨季山林，就用慢日换茵他侬。连续降雨时留在城里看展、上课或按摩。',slots:['晴 / 小雨｜峰顶→Ang Ka→瀑布','中雨｜烹饪课 + SPA','暴雨｜取消山区，回老城和宁曼'],ids:['doi-inthanon','wachirathan','lanna-museum'],segments:[['包车','50–70 分'],['包车回城','约 2 小时']]},
  cmToBkk:{title:'飞曼谷，傍晚从唐人街开始',tag:'核心',area:'上午跨城，傍晚只在 Talat Noi 与 Yaowarat',summary:'我会先选中午前后的航班，把傍晚还给我们。入住以后从旧巷慢慢走到唐人街，不急着看王城。',slots:['上午｜CNX 起飞，确认落地 BKK 还是 DMK','下午｜入住 MRT / BTS 沿线','傍晚｜Talat Noi→Yaowarat 分着吃'],ids:['talat-noi','yaowarat','jok-prince'],segments:[['步行','20–30 分'],['Grab / 步行','15–25 分']]},
  cmJjToBkk:{title:'周末早上逛 JJ，再飞曼谷',tag:'核心',area:'清迈北城早市；中午后只做机场与跨城接驳',summary:'日期正好落在周末，JJ 才值得占这个早上。我们 10:30–11:00 离开，回酒店拿行李，选 14:00 之后的航班。',slots:['06:30–10:30｜JJ 吃早餐、逛农产与手作','11:00｜回酒店取行李→CNX','下午｜飞曼谷，晚上住处附近吃饭'],ids:['jing-jai'],alternatives:[{id:'nong-ho',label:'更想淘二手旧物就用它替换 JJ'}],choiceNote:'JJ 和 Nong Ho 只选一个。若航班早于 14:00，两个都删。'},
  cmToSukhothai:{title:'清迈到素可泰，用半天换一场落日',tag:'核心',area:'上午跨城，傍晚只骑历史公园中央区',summary:'直达巴士会用掉半天，所以我们只在 8 晚版打开它。放下行李以后骑中央区，不赶外围。',slots:['上午｜直达巴士约 5.5 小时 / 预约包车','下午｜住 Mueang Kao，租自行车','16:30｜玛哈泰寺→沙西寺'],ids:['sukhothai-mahathat','wat-sa-si'],segments:[['自行车','5–10 分']]},
  sukhothaiToBkk:{title:'素可泰晨骑，傍晚飞曼谷',tag:'核心',area:'历史公园中央区向西北，再去机场',summary:'早起看中央区与西春寺，中午喝点东西、回酒店取行李。航班少，最终时刻以出票为准。',slots:['清晨｜中央区→西春寺','中午｜素可泰米粉→咖啡→取行李','下午｜去 THS；傍晚飞 BKK'],ids:['sukhothai-mahathat','wat-si-chum','sukhothai-cafe','ths'],segments:[['自行车 / 嘟嘟车','15–20 分'],['自行车 / 嘟嘟车','10–15 分'],['预约车','35–45 分']]},
  crDayTrip:{title:'清莱三处建筑，当天往返的高强度版本',tag:'可换',area:'清迈往返清莱，城南到城北约 12 小时',summary:'这不是减少寺庙，而是把清迈两座寺庙换成白庙、蓝庙和黑屋，并增加约 6 小时公路。如果我们更爱当代宗教建筑与摄影，再选它。',slots:['07:00｜清迈出发，先到白庙','中午｜蓝庙→午餐','下午｜黑屋→约 19:00 回清迈'],ids:['white-temple','blue-temple','baan-dam'],segments:[['包车 / 小团','25–40 分'],['包车 / 小团','20–30 分']],choiceNote:'9 月 30 日可以这样换，但次日大象项目又要早起。若容易晕车或想把旅行走慢，我不建议连续两天早出晚归。'},
  crTransfer:{title:'清迈到清莱，住一晚再看建筑',tag:'核心',area:'跨城后在清莱市区',summary:'如果我们更想看当代宗教建筑，就用清莱替换素可泰，不能两条都走。',slots:['上午｜巴士约 3–3.5 小时','下午｜入住→蓝庙','晚上｜钟楼与夜市'],ids:['blue-temple','clock-tower'],segments:[['Grab','10–20 分']]},
  crToBkk:{title:'清莱建筑线，晚上飞曼谷',tag:'核心',area:'城南白庙到城北黑屋，必须包车',summary:'白庙和黑屋分在城南北，今天靠包车组织，不临时拼景点。',slots:['08:00｜白庙','11:30｜午餐→黑屋','傍晚｜CEI→曼谷'],ids:['white-temple','baan-dam','cei'],segments:[['包车','45–60 分'],['包车','20–30 分']]},
  bkkRoyal:{title:'大皇宫、卧佛寺、摆渡船和郑王庙一条走完',tag:'核心',area:'Rattanakosin 王城与湄南河两岸',summary:'你找的景点顺序是对的，我只改交通入口。511 不是全城通用，酒店在沿线才从 After Khok Wua 下车，否则优先 MRT Sanam Chai。',slots:['08:00｜511 可选下车点→08:30 大皇宫','11:15｜步行到卧佛寺→午餐休息','14:30｜Tha Tien 摆渡→郑王庙'],ids:['after-khok-wua','grand-palace','wat-pho','tha-tien','wat-arun'],segments:[['步行','约 15 分'],['步行','12–18 分'],['步行','5–10 分'],['过河摆渡','约 5 分','https://www.google.com/maps/search/?api=1&query=Tha+Tien+Pier+to+Wat+Arun+Ferry']],alternatives:[{id:'flower-market',label:'还有体力才加花市'}],choiceNote:'住处不在 511 沿线时，不要为了复刻公交攻略先绕去 Khok Wua。打开当天实时公交或直接坐 MRT。'},
  bkkPaknam:{title:'水门寺大佛，从小巷正面走到吞武里屋顶',tag:'核心',area:'Phasi Charoen 与 Talat Phlu，半天步行小圈',summary:'这条线最适合 10 点后出发，把五个机位串成一个社区散步。Mama Cooking 应改为 Mama Cafe，桥位也只走公共道路。',slots:['10:00｜Mama Cafe→Wat Pradu','11:30｜水门寺与塔内玻璃佛塔','14:00｜公共桥位→AT TALAT PHLU'],ids:['mama-cafe','wat-pradu','wat-paknam','wat-paknam-bridge','at-talat-phlu'],segments:[['步行','5–10 分'],['步行','5–8 分'],['步行','8–12 分'],['步行','8–12 分']],choiceNote:'不用把厕所出口和商贩后巷当固定捷径。找不到公共出口就删桥位，照片不值得闯进别人生活空间。'},
  bkkMaeklongFast:{title:'丹嫩清晨加美功列车，想两处都看就这样走',tag:'可换',area:'曼谷西南远郊，约 11–12 小时',summary:'全火车 11:10 才到美功，再去丹嫩已经错过最好时段。效率版要 06:00 包车先到丹嫩，再去美功看 11:10 到站和 11:30 发车。',slots:['06:00｜包车 / 正规小团离开曼谷','07:15–08:45｜丹嫩；再开车去美功','10:15–11:40｜市场与列车→面包车返程'],ids:['damnoen-saduak','maeklong-market','samutsongkhram-bus'],segments:[['包车','约 40–55 分'],['步行','5–10 分']],choiceNote:'这是“两个都要”的效率版，代价是早起、商业化水上市场和一整天公路。若你更在乎旅途本身，改选全程小火车。'},
  bkkMaeklongRail:{title:'全程小火车去美功，把转场本身当旅行',tag:'可换',area:'Wongwian Yai 经 Mahachai、渡轮与 Ban Laem 到美功',summary:'这正是你找到的 DIY 走法。当前时刻可接 07:40、渡轮和 10:10 两段火车，11:10 随列车进市场；这版不再追加丹嫩。',slots:['07:40–08:39｜Wongwian Yai→Mahachai','08:40–09:45｜穿市场→渡轮→Ban Laem','10:10–11:10｜坐进美功；午后返曼谷'],ids:['wongwian-yai-srt','mahachai-station','mahachai-ferry','ban-laem-station','maeklong-market'],segments:[['普通列车','59 分','https://ttsview.railway.co.th/timetable_modern.php?line=5&ln=en&trip=1'],['步行','10–15 分'],['渡轮 + 步行','25–40 分'],['普通列车','60 分','https://ttsview.railway.co.th/timetable_modern.php?line=6&ln=th&trip=1']],alternatives:[{id:'damnoen-saduak',label:'若两处都要，请改选效率版'}],choiceNote:'当前衔接看起来顺，但普通列车时刻会调整。前一晚重新核 SRT，错过 10:10 就不要临时追丹嫩。'},
  bkkAyutthaya:{title:'大城当日往返，用整天换王朝遗址',tag:'可换',area:'曼谷北侧约 80 公里，大城遗址分散',summary:'如果素可泰没去，又想补一段阿瑜陀耶历史，可以拿一个曼谷日来换。正午很热，三处已经足够。',slots:['早上｜火车 / 包车到大城','上午｜Wat Mahathat→Wat Phra Si Sanphet','傍晚｜Wat Chaiwatthanaram→回曼谷'],ids:['ayutthaya-mahathat','ayutthaya-sanphet','ayutthaya-chai'],segments:[['嘟嘟车 / 自行车','8–15 分'],['嘟嘟车','15–25 分']],choiceNote:'如果已经选素可泰，就不要再选大城。两段遗址会挤掉曼谷真正不同的城市体验。'},
  bkkOld:{title:'Talat Noi、河岸和唐人街',tag:'核心',area:'华蓬南侧到 Yaowarat，同一片老城步行圈',summary:'下午才出门，在老仓库、修车巷和河岸之间慢慢走到 Yaowarat。我们分着吃，不排十家店。',slots:['下午｜Wat Traimit→Talat Noi','傍晚｜河岸与老街随走随停','晚上｜Yaowarat 每站只点一两样'],ids:['wat-traimit','talat-noi','yaowarat'],segments:[['步行','20–30 分'],['步行','20–35 分']]},
  bkkArts:{title:'现代曼谷，木屋、当代艺术和公园',tag:'可换',area:'Siam 文化圈，天晴再向东去 Benjakitti',summary:'这是最完整的雨天线。BACC 周一闭馆；天晴又有体力，傍晚再去公园。',slots:['上午｜Jim Thompson House','下午｜BACC→Siam','傍晚｜Benjakitti 或 Mahanakhon'],ids:['jim-thompson','bacc','benjakitti','mahanakhon'],segments:[['步行','8–12 分'],['BTS / MRT / Grab','25–40 分'],['MRT / Grab','20–35 分']]},
  bkkWeekend:{title:'周末市场半日，再回现代曼谷',tag:'可换',area:'Chatuchak 小圈，下午回 Siam',summary:'只有周末才打开。我们 09:00 到，中午去 Or Tor Kor，14:00 前离开闷热的人群。',slots:['09:00｜Chatuchak 先逛目标区','12:00｜Or Tor Kor 午饭','下午｜BACC / Siam'],ids:['chatuchak','or-tor-kor','bacc'],segments:[['步行','8–12 分'],['MRT','25–35 分']]},
  departure:{title:'离开曼谷，今天不赌远路',tag:'核心',area:'酒店到机场，没有固定游览圈',summary:'航班时间还没定，默认不跨河也不去远郊。晚班机才在住处附近喝咖啡或散步。',slots:['BKK｜轨道交通高峰另加 20–30 分钟','DMK｜Red Line 或出租车','国际航班｜约提前 3 小时到机场'],ids:[]}
};

const bkkChoiceKeys=new Set(['bkkPaknam','bkkMaeklongFast','bkkMaeklongRail','bkkOld','bkkArts','bkkAyutthaya']);
const transferKey=date=>[0,6].includes(date.getDay())?'cmJjToBkk':'cmToBkk';
function buildKeys(nights,arrival,northMode='deep',bkkChoice='bkkPaknam'){
  const firstDay=northMode==='chiangrai-day'?'crDayTrip':'cmOld';
  const bkk=bkkChoiceKeys.has(bkkChoice)?bkkChoice:'bkkPaknam';
  if(nights===8&&northMode==='sukhothai')return ['arrival','cmOld','cmElephant','cmWest','cmToSukhothai','sukhothaiToBkk','bkkRoyal',bkk,'departure'];
  if(nights===8&&northMode==='chiangrai-overnight')return ['arrival','cmOld','cmElephant','cmWest','crTransfer','crToBkk','bkkRoyal',bkk,'departure'];
  if(nights<=5)return ['arrival',firstDay,'cmElephant',transferKey(add(arrival,3)),'bkkRoyal','departure'];
  if(nights===6)return ['arrival',firstDay,'cmElephant',transferKey(add(arrival,3)),'bkkRoyal',bkk,'departure'];
  if(nights===7)return ['arrival',firstDay,'cmElephant','cmWest',transferKey(add(arrival,4)),'bkkRoyal',bkk,'departure'];
  return ['arrival',firstDay,'cmElephant','cmWest','cmSlowNight',transferKey(add(arrival,5)),'bkkRoyal',bkk,'departure'];
}

let map,dayMap,markers=[],dayLayers=[],activeCity='all',currentPlan=[],currentArrival,activeDay=0;
function mapIcon(place,number){const c=typeColors[place.type];const glyph=number||({food:'食',drink:'咖',indoor:'雨',transport:'行'}[place.type]||'•');return L.divIcon({className:'',html:`<div class="map-pin${number?' numbered':''}" style="background:${c}">${glyph}</div>`,iconSize:[number?32:28,number?32:28],iconAnchor:[number?16:14,number?16:14],popupAnchor:[0,-15]})}
function popup(place){const image=commonsImage(place.imageFile);return `<div class="popup">${image?`<button class="popup-photo" data-open-place="${place.id}" aria-label="先看看 ${place.name} 长什么样"><img src="${image}" alt="${place.name}" loading="lazy"></button>`:''}<span class="popup-tag">${cityLabels[place.city]} · ${typeLabels[place.type]}</span><h4>${place.name}</h4><p>${place.why||place.desc}</p><div class="popup-actions"><button data-open-place="${place.id}">打开完整介绍</button><a target="_blank" rel="noopener" href="${mapsSearch(place)}">地图导航 ↗</a></div></div>`}
function bindPopupActions(){setTimeout(()=>document.querySelectorAll('[data-open-place]').forEach(el=>{if(!el.dataset.bound){el.dataset.bound='1';el.addEventListener('click',e=>{e.preventDefault();openPlaceDetail(el.dataset.openPlace)})}}),0)}
function renderMarkers(city='all'){
  markers.forEach(m=>map.removeLayer(m.marker));markers=[];
  const visible=places.filter(x=>city==='all'||x.city===city);
  visible.forEach(place=>{const marker=L.marker([place.lat,place.lng],{icon:mapIcon(place)}).addTo(map).bindPopup(popup(place));marker.on('popupopen',bindPopupActions);markers.push({id:place.id,city:place.city,marker})});
  if(visible.length)map.fitBounds(visible.map(x=>[x.lat,x.lng]),{padding:[34,34],maxZoom:city==='all'?6:13});
}
function focusPlace(id){const place=p(id);if(!place||!map)return;activeCity=place.city;setActiveChip(activeCity);renderMarkers(activeCity);setTimeout(()=>{const x=markers.find(m=>m.id===id);if(x){map.setView([place.lat,place.lng],14,{animate:true});x.marker.openPopup()}document.querySelector('#map-section')?.scrollIntoView({behavior:'smooth'})},100)}
function focusCity(city){activeCity=city;setActiveChip(city);renderMarkers(city);document.querySelector('#map-section')?.scrollIntoView({behavior:'smooth'})}
function setActiveChip(city){document.querySelectorAll('[data-city]').forEach(x=>x.classList.toggle('active',x.dataset.city===city))}

function renderPlan(){
  const a=localDate(document.querySelector('#arrivalSelect').value),d=localDate(document.querySelector('#departureSelect').value);const nights=Math.round((d-a)/DAY);
  if(nights<5||nights>8){document.querySelector('#planSummary').innerHTML='<span class="summary-chip alert">请选择 5–8 晚范围</span>';return}
  const requestedNorth=document.querySelector('#northRouteSelect')?.value||'deep';let north=requestedNorth;const alerts=[];
  if(['sukhothai','chiangrai-overnight'].includes(north)&&nights<8){north='deep';alerts.push('住一晚的第三城需要 8 晚，这版先保留清迈深玩')}
  let bkk=document.querySelector('#bangkokRouteSelect')?.value||'bkkPaknam';
  if(north==='sukhothai'&&bkk==='bkkAyutthaya'){bkk='bkkPaknam';alerts.push('已经去素可泰，就不再叠加大城；曼谷第二日改回水门寺')}
  let keys=buildKeys(nights,a,north,bkk);if(keys.length!==nights+1)keys=keys.slice(0,nights).concat('departure');currentPlan=keys;currentArrival=a;activeDay=Math.min(activeDay,keys.length-1);
  const northLabels={deep:'清迈深玩', 'chiangrai-day':'清莱当日往返',sukhothai:'素可泰住一晚','chiangrai-overnight':'清莱住一晚'};
  const bkkLabels={bkkPaknam:'水门寺与 Talat Phlu',bkkMaeklongFast:'丹嫩 + 美功效率版',bkkMaeklongRail:'美功全程小火车',bkkOld:'Talat Noi + 唐人街',bkkArts:'Siam 艺术雨天线',bkkAyutthaya:'大城当日往返'};
  const planType=nights<=5?'压缩版，清迈两整天加曼谷王城':nights===6?'双城标准版，两个完整曼谷日':nights===7?'我最推荐的平衡版':'完整弹性版';
  if(nights===5)alerts.push('只有一个完整曼谷日，第二路线选择暂不进入日程');
  if(north==='chiangrai-day')alerts.push('清莱日约 12 小时，第二天大象项目仍要早起');
  if(keys.includes('cmJjToBkk'))alerts.push('飞曼谷日落在周末，已打开 JJ 早市；航班要选 14:00 后');
  const bkkIndex=keys.indexOf(bkk);if(bkk==='bkkArts'&&bkkIndex>0&&add(a,bkkIndex).getDay()===1)alerts.push('BACC 周一闭馆，这天只走 Jim Thompson + Siam 室内线');
  document.querySelector('#planSummary').innerHTML=`<span class="summary-chip">${nights} 晚 · ${planType}</span><span class="summary-chip">${zhDate(a)} → ${zhDate(d)}</span><span class="summary-chip">北部：${northLabels[north]}</span>${nights>5?`<span class="summary-chip">曼谷第二日：${bkkLabels[bkk]}</span>`:''}${alerts.map(x=>`<span class="summary-chip alert">${x}</span>`).join('')}`;
  document.querySelector('#timeline').innerHTML=keys.map((key,i)=>{const def=dayDefs[key],date=add(a,i);const slots=def.slots.map(s=>{const [label,...rest]=s.split('｜');return `<div class="slot"><b>${label}</b>${rest.join('｜')}</div>`}).join('');const locs=def.ids.map(id=>`<button class="place-link" data-detail-place="${id}">${p(id).name}</button>`).join(' · ');return `<article class="day-card"><div class="day-date"><b>${String(date.getMonth()+1).padStart(2,'0')}.${String(date.getDate()).padStart(2,'0')}</b><span>${week(date)} · D${i}</span></div><div class="day-body"><div class="day-title"><h3>${def.title}</h3><span class="tag ${def.tag==='可换'?'swap':''}">${def.tag}</span></div><p>${def.summary}${locs?`<br><span class="inline-locs">地点：${locs}</span>`:''}</p><div class="slots">${slots}</div><button class="day-map-button" data-day-index="${i}">${def.ids.length?'看这一天怎么走':'看这一天为什么不排路线'} →</button></div></article>`}).join('');
  document.querySelectorAll('[data-detail-place]').forEach(btn=>btn.addEventListener('click',()=>openPlaceDetail(btn.dataset.detailPlace)));
  document.querySelectorAll('[data-day-index]').forEach(btn=>btn.addEventListener('click',()=>{activeDay=Number(btn.dataset.dayIndex);renderDayMap(activeDay);document.querySelector('#day-map-shell')?.scrollIntoView({behavior:'smooth',block:'start'})}));
  renderDayTabs();renderDayMap(activeDay);localStorage.setItem('thaiTripPrefs',JSON.stringify({arrival:iso(a),departure:iso(d),north:requestedNorth,bangkok:document.querySelector('#bangkokRouteSelect')?.value||bkk}));updateForecast(a,d);
}

function renderDayTabs(){
  const tabs=document.querySelector('#dayTabs');if(!tabs)return;
  tabs.innerHTML=currentPlan.map((key,i)=>{const date=add(currentArrival,i);return `<button class="day-tab ${i===activeDay?'active':''}" data-day-tab="${i}"><span>D${i}</span>${date.getMonth()+1}.${date.getDate()}</button>`}).join('');
  tabs.querySelectorAll('[data-day-tab]').forEach(btn=>btn.addEventListener('click',()=>{activeDay=Number(btn.dataset.dayTab);renderDayTabs();renderDayMap(activeDay)}));
}
function renderDayMap(index){
  const key=currentPlan[index],def=dayDefs[key];if(!def||!dayMap)return;activeDay=index;renderDayTabs();
  document.querySelector('#dayMapTitle').textContent=`D${index} · ${def.title}`;document.querySelector('#dayMapIntro').textContent=def.area;
  dayLayers.forEach(layer=>dayMap.removeLayer(layer));dayLayers=[];
  const routePlaces=def.ids.map(p).filter(Boolean);const list=document.querySelector('#dayRouteList');const stats=document.querySelector('#dayRouteStats'),choices=document.querySelector('#dayChoices');
  if(choices){const cards=(def.alternatives||[]).map(a=>{const place=p(a.id),image=commonsImage(place?.imageFile);return `<button class="route-choice-card" data-detail-place="${a.id}">${image?`<img src="${image}" alt="${place.name}" loading="lazy">`:''}<span><b>${a.label}</b><small>${place.name}</small></span></button>`}).join('');choices.innerHTML=`${def.choiceNote?`<p>${def.choiceNote}</p>`:''}${cards?`<div class="route-choice-grid">${cards}</div>`:''}`;choices.querySelectorAll('[data-detail-place]').forEach(btn=>btn.addEventListener('click',()=>openPlaceDetail(btn.dataset.detailPlace)))}
  if(!routePlaces.length){list.innerHTML='<li class="empty-route">抵达和离开日不固定住处，也就不画一条假路线。等酒店和航班确定后，我们只看当时最稳的接驳。</li>';stats.innerHTML='<span>0 个固定停靠点</span><b>今天不跨区找景点</b>';dayMap.setView(key==='arrival'?[18.79,98.99]:[13.75,100.52],12);return}
  routePlaces.forEach((place,i)=>{const marker=L.marker([place.lat,place.lng],{icon:mapIcon(place,i+1)}).addTo(dayMap).bindPopup(popup(place));marker.on('popupopen',bindPopupActions);dayLayers.push(marker)});
  if(routePlaces.length>1){const line=L.polyline(routePlaces.map(x=>[x.lat,x.lng]),{color:'#dd8a2d',weight:3,dashArray:'8 9',opacity:.9}).addTo(dayMap);dayLayers.push(line)}
  dayMap.fitBounds(routePlaces.map(x=>[x.lat,x.lng]),{padding:[38,38],maxZoom:14});
  stats.innerHTML=`<span>${routePlaces.length} 个主线停靠点${def.alternatives?.length?` · ${def.alternatives.length} 个可换点`:''}</span><b>${def.area}</b>`;
  list.innerHTML=routePlaces.map((place,i)=>{const seg=i<routePlaces.length-1?(def.segments||[])[i]||['按现场选择','时间待定']:null;const next=routePlaces[i+1];const routeUrl=seg?(seg[2]||mapsRoute(place,next,seg[0].includes('步行')?'walking':'driving')):'';return `<li><div class="route-stop"><span>${i+1}</span><button data-detail-place="${place.id}"><b>${place.name}</b><small>${place.desc}</small></button></div>${seg?`<div class="route-leg"><i></i><span>${seg[0]} · ${seg[1]}</span><a href="${routeUrl}" target="_blank" rel="noopener">打开这一段导航 ↗</a></div>`:''}</li>`}).join('');
  list.querySelectorAll('[data-detail-place]').forEach(btn=>btn.addEventListener('click',()=>openPlaceDetail(btn.dataset.detailPlace)));
}

function sourceMarkup(place){const sources=place.sources||[lp];return sources.map(s=>s.url?`<a href="${s.url}" target="_blank" rel="noopener"><span>${s.kind||'来源'}</span>${s.title} ↗</a>`:`<div><span>书本</span>${s.title}<small>${s.note||''}</small></div>`).join('')}
function detailMarkup(place,{standalone=false}={}){const image=commonsImage(place.imageFile);return `${image?`<figure class="detail-hero"><img src="${image}" alt="${place.name}"><figcaption>图片来自 Wikimedia Commons · <a href="${commonsPage(place.imageFile)}" target="_blank" rel="noopener">查看原文件与授权</a></figcaption></figure>`:''}<div class="detail-kicker">${cityLabels[place.city]} · ${typeLabels[place.type]}</div><h1>${place.name}</h1><p class="detail-lead">${place.why||place.desc}</p><div class="detail-grid"><section><h2>我们到了先看什么</h2>${place.lookFor?`<ol>${place.lookFor.map(x=>`<li>${x}</li>`).join('')}</ol>`:`<p>${place.desc}</p>`}</section><section><h2>为什么会是现在这样</h2><p>${place.story||'这里还没有写成一段可靠的长介绍。出发前我会再看官方资料，不拿传闻把它补满。'}</p></section><section><h2>放在这一天怎么走</h2><p>${place.together||'它现在是备选点。只有当天路线、天气和体力都合适，我们才把它打开。'}</p></section><section><h2>如果下雨</h2><p>${place.rain||'先看现场雨势和道路。短雨可以等，雷雨、积水或湿滑明显时直接取消。'}</p></section></div>${place.current?.length?`<section class="current-box"><h2>现在能确认的事</h2><ul>${place.current.map(x=>`<li>${x}</li>`).join('')}</ul><p>这些信息核到 2026-08-14，临近出发再点下面的官方页面。</p></section>`:''}<div class="detail-actions"><a class="button primary" href="${mapsSearch(place)}" target="_blank" rel="noopener">从这里开始导航 ↗</a>${standalone?'<a class="button ghost" href="index.html#map-section">回到行程地图</a>':`<a class="button ghost" href="place.html?id=${place.id}">在独立页面打开</a>`}</div><section class="detail-sources"><h2>我参考了什么</h2>${sourceMarkup(place)}</section>`}
function openPlaceDetail(id){const place=p(id),drawer=document.querySelector('#placeDrawer');if(!place)return;if(!drawer){location.href=`place.html?id=${id}`;return}document.querySelector('#placeDrawerContent').innerHTML=detailMarkup(place);drawer.hidden=false;document.body.classList.add('drawer-open');history.replaceState(null,'',`#place=${id}`);drawer.querySelector('.drawer-close').focus()}
function closePlaceDetail(){const drawer=document.querySelector('#placeDrawer');if(!drawer)return;drawer.hidden=true;document.body.classList.remove('drawer-open');if(location.hash.startsWith('#place='))history.replaceState(null,'',location.pathname+location.search)}

async function updateForecast(arrival,departure){
  const status=document.querySelector('#forecastStatus'),detail=document.querySelector('#forecastDetail');if(!status||!detail)return;
  const now=new Date();now.setHours(12,0,0,0);const days=Math.ceil((arrival-now)/DAY);
  if(days>16){const unlock=add(arrival,-16);status.textContent=`预计 ${zhDate(unlock)} 进入窗口`;detail.textContent='到时页面会自动读取清迈、素可泰和曼谷的降雨概率。现在先按上午户外、下午机动来排。';return}
  if(days<-2){status.textContent='行程日期已过';return}status.textContent='正在获取逐日预报…';
  try{const cities=[['清迈',18.79,98.99],['素可泰',17.01,99.70],['曼谷',13.75,100.52]];const rows=await Promise.all(cities.map(async([name,lat,lng])=>{const url=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lng}&daily=precipitation_probability_max,precipitation_sum,temperature_2m_max,temperature_2m_min&timezone=Asia%2FBangkok&start_date=${iso(arrival)}&end_date=${iso(departure)}`;const j=await fetch(url).then(r=>{if(!r.ok)throw new Error('forecast');return r.json()});const max=Math.max(...j.daily.precipitation_probability_max.filter(Number.isFinite));const rain=j.daily.precipitation_sum.reduce((x,y)=>x+(y||0),0);return `${name}最高降雨概率 ${max}% / 累计约 ${rain.toFixed(0)}mm`;}));status.textContent='逐日预报已可用';detail.textContent=rows.join('；')+'。如果 TMD 发暴雨警报，我们以警报为准。'}catch(e){status.textContent='暂时无法读取预报';detail.textContent='出发前 72 小时直接看 Thai Meteorological Department。'}
}

function init(){
  if(!document.querySelector('#map'))return;
  const arrivalEl=document.querySelector('#arrivalSelect'),departureEl=document.querySelector('#departureSelect'),northEl=document.querySelector('#northRouteSelect'),bangkokEl=document.querySelector('#bangkokRouteSelect'),buildButton=document.querySelector('#buildPlan'),toolbar=document.querySelector('#mapToolbar');
  let saved=null;try{saved=JSON.parse(localStorage.getItem('thaiTripPrefs')||localStorage.getItem('thaiTripDates')||'null')}catch(e){localStorage.removeItem('thaiTripPrefs')}if(saved){if([...arrivalEl.options].some(x=>x.value===saved.arrival))arrivalEl.value=saved.arrival;if([...departureEl.options].some(x=>x.value===saved.departure))departureEl.value=saved.departure;if(northEl&&[...northEl.options].some(x=>x.value===saved.north))northEl.value=saved.north;if(bangkokEl&&[...bangkokEl.options].some(x=>x.value===saved.bangkok))bangkokEl.value=saved.bangkok}
  map=L.map('map',{zoomControl:false,scrollWheelZoom:false}).setView([16.7,99.5],6);L.control.zoom({position:'topright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);renderMarkers();
  dayMap=L.map('dayMap',{zoomControl:false,scrollWheelZoom:false}).setView([18.79,98.99],12);L.control.zoom({position:'topright'}).addTo(dayMap);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(dayMap);
  toolbar.addEventListener('click',e=>{const b=e.target.closest('[data-city]');if(b)focusCity(b.dataset.city)});
  document.querySelectorAll('[data-focus-city]').forEach(b=>b.addEventListener('click',()=>focusCity(b.dataset.focusCity)));document.querySelectorAll('[data-focus-id]').forEach(b=>b.addEventListener('click',()=>focusPlace(b.dataset.focusId)));
  document.querySelector('#placeDrawer .drawer-backdrop')?.addEventListener('click',closePlaceDetail);document.querySelector('#placeDrawer .drawer-close')?.addEventListener('click',closePlaceDetail);document.addEventListener('keydown',e=>{if(e.key==='Escape')closePlaceDetail()});
  buildButton.addEventListener('click',renderPlan);[arrivalEl,departureEl,northEl,bangkokEl].filter(Boolean).forEach(el=>el.addEventListener('change',renderPlan));renderPlan();
  const hashMatch=location.hash.match(/^#place=(.+)$/);if(hashMatch)openPlaceDetail(hashMatch[1]);
}

window.THAILAND_TRIP={places,dayDefs,details,cityLabels,typeLabels,commonsImage,commonsPage,mapsSearch,detailMarkup,p};
document.addEventListener('DOMContentLoaded',init);
